### ISSUE TITLE
Issue-feat: readme

### ISSUE THREAD

**Issue by kazupot7** [kazupot7/token-creator#12]
Automated Review Comments
Issues in README.md:
  - (10, 'Line exceeds 80 characters')
  - (14, 'Line exceeds 80 characters')
Issues in src/views/home/index.tsx:
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (12, 'TODO found')

**Comment by glory1001** [comment]
I got it.
