### ISSUE TITLE
Issue-implement program test rather than using TestValidator

### ISSUE THREAD

**Issue by kazupot7** [kazupot7/token-creator#139]
Automated Review Comments
Issues in .gitpod.yml:
  - (11, 'Line exceeds 80 characters')
Issues in package.json:
  - (4, 'Line exceeds 80 characters')
  - (5, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
Issues in program/Cargo.toml:
  - (1, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
Issues in program/src/lib.rs:
  - (47, 'Line exceeds 80 characters')
Issues in program/tests/integration.rs:
  - (31, 'Line exceeds 80 characters')
  - (40, 'Line exceeds 80 characters')
  - (41, 'Line exceeds 80 characters')

**Comment by Zeusofsky** [comment]
I got it.
