### ISSUE TITLE
Issue-feat: add rust template

### ISSUE THREAD

**Issue by kazupot7** [kazupot7/token-creator#14]
Automated Review Comments
Issues in README.md:
  - (8, 'Line exceeds 80 characters')
  - (39, 'Line exceeds 80 characters')
  - (40, 'Line exceeds 80 characters')
Issues in program/Cargo.toml:
  - (6, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
Issues in program/README.md:
  - (4, 'Line exceeds 80 characters')
Issues in program/scripts/update-solana-dependencies.sh:
  - (30, 'Line exceeds 80 characters')
  - (46, 'Hardcoded string found')
Issues in program/src/lib.rs:
  - (3, 'Line exceeds 80 characters')
  - (53, 'Line exceeds 80 characters')
Issues in program/tests/integration.rs:
  - (21, 'Line exceeds 80 characters')
  - (33, 'Line exceeds 80 characters')

**Comment by billmbowling3** [comment]
I got it.
