### ISSUE TITLE
Issue-Fix Jest test runner
- Update @project-serum/sol-wallet-adapter to latest
  * Fixes superstruct dependency mismatch
- Remove manual types
- Fix typings in Jest tests
  * Load typeRoots from node_modules
- Add global mocks for testing-library rendering
- Update test to check for text that exists

### ISSUE THREAD

**Issue by kazupot7** [kazupot7/token-creator#143]
Automated Review Comments
Issues in package.json:
  - (13, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (17, 'Line exceeds 80 characters')
  - (19, 'Hardcoded string found')
Issues in src/App.test.tsx:
  - (1, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
Issues in src/setupTests.ts:
  - (6, 'Hardcoded string found')
Issues in tsconfig.json:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
Issues in yarn.lock:
  - (7, 'Line exceeds 80 characters')
  - (8, 'Line exceeds 80 characters')
  - (11, 'Line exceeds 80 characters')
  - (12, 'Line exceeds 80 characters')

**Comment by brandonabeal110** [comment]
I got it.
