### ISSUE TITLE
Issue-update @solana packages

### ISSUE THREAD

**Issue by kazupot7** [kazupot7/token-creator#145]
Automated Review Comments
Issues in package.json:
  - (21, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
  - (25, 'Line exceeds 80 characters')
  - (27, 'Hardcoded string found')
Issues in src/App.test.tsx:
  - (1, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
Issues in src/setupTests.ts:
  - (6, 'Hardcoded string found')
Issues in tsconfig.json:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
Issues in yarn.lock:
  - (7, 'Line exceeds 80 characters')
  - (8, 'Line exceeds 80 characters')
  - (11, 'Line exceeds 80 characters')
  - (12, 'Line exceeds 80 characters')
  - (17, 'Line exceeds 80 characters')
  - (18, 'Line exceeds 80 characters')
  - (22, 'Line exceeds 80 characters')
  - (23, 'Line exceeds 80 characters')
  - (26, 'Line exceeds 80 characters')
  - (27, 'Line exceeds 80 characters')
  - (33, 'Line exceeds 80 characters')
  - (34, 'Line exceeds 80 characters')
  - (41, 'Line exceeds 80 characters')
  - (42, 'Line exceeds 80 characters')
  - (49, 'Line exceeds 80 characters')
  - (50, 'Line exceeds 80 characters')
  - (53, 'Line exceeds 80 characters')
  - (54, 'Line exceeds 80 characters')
  - (56, 'Hardcoded string found')
  - (57, 'Hardcoded string found')
  - (58, 'Hardcoded string found')
  - (73, 'Line exceeds 80 characters')
  - (74, 'Line exceeds 80 characters')
  - (77, 'Line exceeds 80 characters')
  - (78, 'Line exceeds 80 characters')
  - (80, 'Hardcoded string found')
  - (81, 'Hardcoded string found')
  - (92, 'Hardcoded string found')
  - (97, 'Line exceeds 80 characters')
  - (98, 'Line exceeds 80 characters')
  - (100, 'Line exceeds 80 characters')
  - (105, 'Line exceeds 80 characters')
  - (106, 'Line exceeds 80 characters')
  - (108, 'Hardcoded string found')
  - (115, 'Line exceeds 80 characters')
  - (116, 'Line exceeds 80 characters')
  - (123, 'Line exceeds 80 characters')
  - (132, 'Line exceeds 80 characters')
  - (133, 'Line exceeds 80 characters')
  - (135, 'Line exceeds 80 characters')
  - (136, 'Line exceeds 80 characters')
  - (140, 'Line exceeds 80 characters')
  - (141, 'Line exceeds 80 characters')
  - (145, 'Line exceeds 80 characters')
  - (152, 'Line exceeds 80 characters')
  - (153, 'Line exceeds 80 characters')
  - (157, 'Line exceeds 80 characters')

**Comment by billmbowling3** [comment]
I got it.
