### ISSUE TITLE
Issue-Merge pull request #33 from solana-labs/dependabot/npm_and_yarn/solana/spl-token-registry-0.2.203

chore(deps): bump @solana/spl-token-registry from 0.2.2 to 0.2.203

### ISSUE THREAD

**Issue by kazupot7** [kazupot7/token-creator#158]
Automated Review Comments
Issues in package-lock.json:
  - (2, 'Line exceeds 80 characters')
  - (2, 'Hardcoded string found')
  - (3, 'Line exceeds 80 characters')
  - (3, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Line exceeds 80 characters')
  - (7, 'Hardcoded string found')
  - (8, 'Line exceeds 80 characters')
  - (8, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (13, 'Line exceeds 80 characters')
  - (13, 'Hardcoded string found')
  - (14, 'Line exceeds 80 characters')
  - (14, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
  - (26, 'Hardcoded string found')
  - (28, 'Hardcoded string found')
  - (30, 'Hardcoded string found')
  - (32, 'Hardcoded string found')
  - (34, 'Hardcoded string found')
  - (35, 'Line exceeds 80 characters')
  - (35, 'Hardcoded string found')
  - (36, 'Line exceeds 80 characters')
  - (36, 'Hardcoded string found')
  - (37, 'Hardcoded string found')
  - (41, 'Hardcoded string found')
  - (45, 'Hardcoded string found')
  - (46, 'Hardcoded string found')
  - (47, 'Hardcoded string found')
  - (52, 'Hardcoded string found')
  - (53, 'Hardcoded string found')
  - (54, 'Hardcoded string found')
  - (56, 'Hardcoded string found')
  - (57, 'Hardcoded string found')
  - (58, 'Hardcoded string found')
  - (59, 'Line exceeds 80 characters')
  - (59, 'Hardcoded string found')
  - (64, 'Hardcoded string found')
  - (65, 'Line exceeds 80 characters')
  - (65, 'Hardcoded string found')
  - (66, 'Line exceeds 80 characters')
  - (66, 'Hardcoded string found')
  - (67, 'Hardcoded string found')
  - (73, 'Hardcoded string found')
  - (74, 'Line exceeds 80 characters')
  - (74, 'Hardcoded string found')
  - (75, 'Line exceeds 80 characters')
  - (75, 'Hardcoded string found')
  - (76, 'Hardcoded string found')
  - (85, 'Hardcoded string found')
  - (86, 'Line exceeds 80 characters')
  - (86, 'Hardcoded string found')
  - (87, 'Line exceeds 80 characters')
  - (87, 'Hardcoded string found')
  - (88, 'Hardcoded string found')
  - (89, 'Line exceeds 80 characters')
  - (89, 'Hardcoded string found')
  - (90, 'Line exceeds 80 characters')
  - (90, 'Hardcoded string found')
  - (91, 'Hardcoded string found')
  - (98, 'Hardcoded string found')
  - (99, 'Line exceeds 80 characters')
  - (99, 'Hardcoded string found')
  - (100, 'Line exceeds 80 characters')
  - (100, 'Hardcoded string found')
  - (103, 'Hardcoded string found')
  - (104, 'Line exceeds 80 characters')
  - (104, 'Hardcoded string found')
  - (105, 'Line exceeds 80 characters')
  - (105, 'Hardcoded string found')
  - (106, 'Hardcoded string found')
  - (107, 'Hardcoded string found')
  - (109, 'Hardcoded string found')
  - (110, 'Hardcoded string found')
  - (111, 'Hardcoded string found')
  - (112, 'Hardcoded string found')
  - (113, 'Line exceeds 80 characters')
  - (113, 'Hardcoded string found')
  - (114, 'Hardcoded string found')
  - (122, 'Hardcoded string found')
  - (123, 'Line exceeds 80 characters')
  - (123, 'Hardcoded string found')
  - (124, 'Line exceeds 80 characters')
  - (124, 'Hardcoded string found')
  - (125, 'Hardcoded string found')
  - (126, 'Line exceeds 80 characters')
  - (126, 'Hardcoded string found')
  - (127, 'Line exceeds 80 characters')
  - (127, 'Hardcoded string found')
  - (128, 'Hardcoded string found')
  - (134, 'Hardcoded string found')
  - (136, 'Hardcoded string found')
  - (137, 'Hardcoded string found')
  - (138, 'Hardcoded string found')
  - (140, 'Hardcoded string found')
  - (142, 'Hardcoded string found')
  - (143, 'Line exceeds 80 characters')
  - (143, 'Hardcoded string found')
  - (144, 'Line exceeds 80 characters')
  - (144, 'Hardcoded string found')
  - (145, 'Hardcoded string found')
  - (149, 'Hardcoded string found')
  - (153, 'Hardcoded string found')
  - (154, 'Hardcoded string found')
  - (158, 'Hardcoded string found')
  - (159, 'Hardcoded string found')
  - (160, 'Hardcoded string found')
  - (163, 'Hardcoded string found')
  - (164, 'Hardcoded string found')
  - (165, 'Hardcoded string found')
  - (166, 'Line exceeds 80 characters')
  - (166, 'Hardcoded string found')
  - (167, 'Hardcoded string found')
  - (168, 'Hardcoded string found')
  - (169, 'Line exceeds 80 characters')
  - (169, 'Hardcoded string found')
  - (170, 'Hardcoded string found')
  - (176, 'Hardcoded string found')
  - (177, 'Hardcoded string found')
  - (178, 'Hardcoded string found')
  - (179, 'Line exceeds 80 characters')
  - (179, 'Hardcoded string found')
  - (184, 'Hardcoded string found')
  - (185, 'Line exceeds 80 characters')
  - (185, 'Hardcoded string found')
  - (186, 'Line exceeds 80 characters')
  - (186, 'Hardcoded string found')
  - (187, 'Hardcoded string found')
  - (188, 'Line exceeds 80 characters')
  - (188, 'Hardcoded string found')
  - (189, 'Line exceeds 80 characters')
  - (189, 'Hardcoded string found')
  - (190, 'Hardcoded string found')
  - (196, 'Hardcoded string found')
  - (197, 'Line exceeds 80 characters')
  - (197, 'Hardcoded string found')
  - (198, 'Line exceeds 80 characters')
  - (198, 'Hardcoded string found')
  - (199, 'Hardcoded string found')
  - (200, 'Line exceeds 80 characters')
  - (200, 'Hardcoded string found')
  - (201, 'Line exceeds 80 characters')
  - (201, 'Hardcoded string found')
  - (202, 'Hardcoded string found')
  - (208, 'Hardcoded string found')
  - (209, 'Hardcoded string found')
  - (211, 'Hardcoded string found')
  - (213, 'Hardcoded string found')
  - (215, 'Hardcoded string found')
  - (216, 'Line exceeds 80 characters')
  - (216, 'Hardcoded string found')
  - (217, 'Line exceeds 80 characters')
  - (217, 'Hardcoded string found')
  - (218, 'Hardcoded string found')
  - (222, 'Hardcoded string found')
  - (226, 'Hardcoded string found')
  - (227, 'Hardcoded string found')
  - (231, 'Hardcoded string found')
  - (232, 'Hardcoded string found')
  - (233, 'Hardcoded string found')
  - (236, 'Hardcoded string found')
  - (237, 'Hardcoded string found')
  - (238, 'Hardcoded string found')
  - (239, 'Line exceeds 80 characters')
  - (239, 'Hardcoded string found')
  - (240, 'Hardcoded string found')
  - (244, 'Hardcoded string found')
  - (245, 'Hardcoded string found')
  - (246, 'Hardcoded string found')
  - (247, 'Line exceeds 80 characters')
  - (247, 'Hardcoded string found')
  - (252, 'Hardcoded string found')
  - (253, 'Line exceeds 80 characters')
  - (253, 'Hardcoded string found')
  - (254, 'Line exceeds 80 characters')
  - (254, 'Hardcoded string found')
  - (255, 'Hardcoded string found')
  - (256, 'Line exceeds 80 characters')
  - (256, 'Hardcoded string found')
  - (257, 'Line exceeds 80 characters')
  - (257, 'Hardcoded string found')
  - (258, 'Hardcoded string found')
  - (263, 'Hardcoded string found')
  - (265, 'Hardcoded string found')
  - (267, 'Hardcoded string found')
  - (270, 'Hardcoded string found')
  - (271, 'Hardcoded string found')
  - (272, 'Hardcoded string found')
  - (275, 'Hardcoded string found')
  - (280, 'Hardcoded string found')
  - (281, 'Hardcoded string found')
  - (282, 'Hardcoded string found')
  - (284, 'Hardcoded string found')
  - (285, 'Hardcoded string found')
  - (286, 'Hardcoded string found')
  - (287, 'Hardcoded string found')
  - (288, 'Line exceeds 80 characters')
  - (288, 'Hardcoded string found')
  - (289, 'Hardcoded string found')
  - (294, 'Hardcoded string found')
  - (295, 'Hardcoded string found')
  - (300, 'Hardcoded string found')
  - (301, 'Hardcoded string found')
  - (302, 'Line exceeds 80 characters')
  - (302, 'Hardcoded string found')
  - (303, 'Hardcoded string found')
  - (304, 'Hardcoded string found')
  - (311, 'Hardcoded string found')
  - (312, 'Line exceeds 80 characters')
  - (312, 'Hardcoded string found')
  - (313, 'Line exceeds 80 characters')
  - (313, 'Hardcoded string found')
  - (314, 'Hardcoded string found')
  - (315, 'Line exceeds 80 characters')
  - (315, 'Hardcoded string found')
  - (316, 'Line exceeds 80 characters')
  - (316, 'Hardcoded string found')
  - (317, 'Hardcoded string found')
  - (321, 'Line exceeds 80 characters')
  - (321, 'Hardcoded string found')
  - (324, 'Hardcoded string found')
  - (325, 'Line exceeds 80 characters')
  - (325, 'Hardcoded string found')
  - (326, 'Line exceeds 80 characters')
  - (326, 'Hardcoded string found')
  - (327, 'Hardcoded string found')
  - (328, 'Line exceeds 80 characters')
  - (328, 'Hardcoded string found')
  - (329, 'Line exceeds 80 characters')
  - (329, 'Hardcoded string found')
  - (330, 'Hardcoded string found')
  - (337, 'Hardcoded string found')
  - (338, 'Line exceeds 80 characters')
  - (338, 'Hardcoded string found')
  - (339, 'Line exceeds 80 characters')
  - (339, 'Hardcoded string found')
  - (340, 'Hardcoded string found')
  - (341, 'Line exceeds 80 characters')
  - (341, 'Hardcoded string found')
  - (342, 'Line exceeds 80 characters')
  - (342, 'Hardcoded string found')
  - (345, 'Hardcoded string found')
  - (347, 'Line exceeds 80 characters')
  - (347, 'Hardcoded string found')
  - (350, 'Hardcoded string found')
  - (351, 'Hardcoded string found')
  - (352, 'Line exceeds 80 characters')
  - (352, 'Hardcoded string found')
  - (353, 'Hardcoded string found')
  - (354, 'Hardcoded string found')
  - (355, 'Line exceeds 80 characters')
  - (355, 'Hardcoded string found')
  - (358, 'Hardcoded string found')
  - (359, 'Line exceeds 80 characters')
  - (359, 'Hardcoded string found')
  - (360, 'Line exceeds 80 characters')
  - (360, 'Hardcoded string found')
  - (361, 'Hardcoded string found')
  - (362, 'Line exceeds 80 characters')
  - (362, 'Hardcoded string found')
  - (363, 'Line exceeds 80 characters')
  - (363, 'Hardcoded string found')
  - (366, 'Hardcoded string found')
  - (372, 'Hardcoded string found')
  - (373, 'Hardcoded string found')
  - (374, 'Line exceeds 80 characters')
  - (374, 'Hardcoded string found')
  - (375, 'Hardcoded string found')
  - (380, 'Hardcoded string found')
  - (381, 'Line exceeds 80 characters')
  - (381, 'Hardcoded string found')
  - (387, 'Hardcoded string found')
  - (388, 'Line exceeds 80 characters')
  - (388, 'Hardcoded string found')
  - (389, 'Hardcoded string found')
  - (391, 'Hardcoded string found')
  - (392, 'Hardcoded string found')
  - (393, 'Hardcoded string found')
  - (395, 'Hardcoded string found')
  - (396, 'Hardcoded string found')
  - (398, 'Hardcoded string found')
  - (399, 'Hardcoded string found')
  - (400, 'Hardcoded string found')
  - (401, 'Line exceeds 80 characters')
  - (401, 'Hardcoded string found')
  - (402, 'Hardcoded string found')
  - (410, 'Hardcoded string found')
  - (411, 'Line exceeds 80 characters')
  - (411, 'Hardcoded string found')
  - (415, 'Hardcoded string found')
  - (416, 'Hardcoded string found')
  - (417, 'Hardcoded string found')
  - (418, 'Line exceeds 80 characters')
  - (418, 'Hardcoded string found')
  - (419, 'Hardcoded string found')
  - (420, 'Hardcoded string found')
  - (421, 'Line exceeds 80 characters')
  - (421, 'Hardcoded string found')
  - (422, 'Hardcoded string found')
  - (426, 'Hardcoded string found')
  - (427, 'Line exceeds 80 characters')
  - (427, 'Hardcoded string found')
  - (429, 'Hardcoded string found')
  - (430, 'Hardcoded string found')
  - (431, 'Hardcoded string found')
  - (432, 'Hardcoded string found')
  - (433, 'Hardcoded string found')
  - (436, 'Hardcoded string found')
  - (452, 'Hardcoded string found')
  - (453, 'Hardcoded string found')
  - (454, 'Hardcoded string found')
  - (459, 'Hardcoded string found')
  - (460, 'Line exceeds 80 characters')
  - (460, 'Hardcoded string found')
  - (461, 'Line exceeds 80 characters')
  - (461, 'Hardcoded string found')
  - (462, 'Hardcoded string found')
  - (463, 'Line exceeds 80 characters')
  - (463, 'Hardcoded string found')
  - (464, 'Line exceeds 80 characters')
  - (464, 'Hardcoded string found')
  - (465, 'Hardcoded string found')
  - (469, 'Hardcoded string found')
  - (473, 'Hardcoded string found')
  - (474, 'Line exceeds 80 characters')
  - (474, 'Hardcoded string found')
  - (475, 'Hardcoded string found')
  - (476, 'Hardcoded string found')
  - (477, 'Hardcoded string found')
  - (479, 'Hardcoded string found')
  - (484, 'Hardcoded string found')
  - (485, 'Line exceeds 80 characters')
  - (485, 'Hardcoded string found')
  - (491, 'Hardcoded string found')
  - (492, 'Hardcoded string found')
  - (493, 'Line exceeds 80 characters')
  - (493, 'Hardcoded string found')
  - (496, 'Hardcoded string found')
  - (497, 'Line exceeds 80 characters')
  - (497, 'Hardcoded string found')
  - (502, 'Hardcoded string found')
  - (503, 'Hardcoded string found')
  - (504, 'Hardcoded string found')
  - (505, 'Line exceeds 80 characters')
  - (505, 'Hardcoded string found')
  - (508, 'Hardcoded string found')
  - (509, 'Line exceeds 80 characters')
  - (509, 'Hardcoded string found')
  - (515, 'Hardcoded string found')
  - (516, 'Line exceeds 80 characters')
  - (516, 'Hardcoded string found')
  - (517, 'Hardcoded string found')
  - (518, 'Hardcoded string found')
  - (519, 'Hardcoded string found')
  - (522, 'Hardcoded string found')
  - (524, 'Hardcoded string found')
  - (525, 'Line exceeds 80 characters')
  - (525, 'Hardcoded string found')
  - (526, 'Hardcoded string found')
  - (527, 'Hardcoded string found')
  - (529, 'Hardcoded string found')
  - (530, 'Hardcoded string found')
  - (533, 'Hardcoded string found')
  - (534, 'Hardcoded string found')
  - (535, 'Line exceeds 80 characters')
  - (535, 'Hardcoded string found')
  - (536, 'Hardcoded string found')
  - (537, 'Hardcoded string found')
  - (543, 'Hardcoded string found')
  - (544, 'Hardcoded string found')
  - (545, 'Hardcoded string found')
  - (547, 'Hardcoded string found')
  - (550, 'Hardcoded string found')
  - (551, 'Hardcoded string found')
  - (552, 'Hardcoded string found')
  - (553, 'Line exceeds 80 characters')
  - (553, 'Hardcoded string found')
  - (554, 'Hardcoded string found')
  - (559, 'Hardcoded string found')
  - (560, 'Line exceeds 80 characters')
  - (560, 'Hardcoded string found')
  - (562, 'Hardcoded string found')
  - (563, 'Hardcoded string found')
  - (566, 'Hardcoded string found')
  - (567, 'Line exceeds 80 characters')
  - (567, 'Hardcoded string found')
  - (568, 'Line exceeds 80 characters')
  - (568, 'Hardcoded string found')
  - (570, 'Hardcoded string found')
  - (571, 'Hardcoded string found')
  - (572, 'Hardcoded string found')
  - (576, 'Hardcoded string found')
  - (577, 'Hardcoded string found')
  - (578, 'Hardcoded string found')
  - (579, 'Line exceeds 80 characters')
  - (579, 'Hardcoded string found')
  - (580, 'Hardcoded string found')
  - (581, 'Hardcoded string found')
  - (582, 'Line exceeds 80 characters')
  - (582, 'Hardcoded string found')
  - (583, 'Hardcoded string found')
  - (589, 'Hardcoded string found')
  - (590, 'Hardcoded string found')
  - (591, 'Hardcoded string found')
  - (593, 'Hardcoded string found')
  - (596, 'Hardcoded string found')
  - (597, 'Hardcoded string found')
  - (598, 'Hardcoded string found')
  - (599, 'Hardcoded string found')
  - (602, 'Hardcoded string found')
  - (608, 'Hardcoded string found')
  - (609, 'Hardcoded string found')
  - (610, 'Line exceeds 80 characters')
  - (610, 'Hardcoded string found')
  - (613, 'Hardcoded string found')
  - (614, 'Hardcoded string found')
  - (615, 'Line exceeds 80 characters')
  - (615, 'Hardcoded string found')
  - (618, 'Hardcoded string found')
  - (619, 'Hardcoded string found')
  - (624, 'Hardcoded string found')
  - (625, 'Hardcoded string found')
  - (626, 'Hardcoded string found')
  - (627, 'Line exceeds 80 characters')
  - (627, 'Hardcoded string found')
  - (628, 'Hardcoded string found')
  - (633, 'Hardcoded string found')
  - (634, 'Hardcoded string found')
  - (635, 'Line exceeds 80 characters')
  - (635, 'Hardcoded string found')
  - (637, 'Hardcoded string found')
  - (638, 'Line exceeds 80 characters')
  - (638, 'Hardcoded string found')
  - (640, 'Hardcoded string found')
  - (641, 'Hardcoded string found')
  - (642, 'Hardcoded string found')
  - (643, 'Hardcoded string found')
  - (644, 'Hardcoded string found')
  - (648, 'Hardcoded string found')
  - (649, 'Hardcoded string found')
  - (650, 'Hardcoded string found')
  - (652, 'Line exceeds 80 characters')
  - (652, 'Hardcoded string found')
  - (653, 'Hardcoded string found')
  - (656, 'Hardcoded string found')
  - (657, 'Line exceeds 80 characters')
  - (657, 'Hardcoded string found')
  - (658, 'Hardcoded string found')
  - (661, 'Hardcoded string found')
  - (662, 'Line exceeds 80 characters')
  - (662, 'Hardcoded string found')
  - (663, 'Hardcoded string found')
  - (666, 'Hardcoded string found')
  - (667, 'Line exceeds 80 characters')
  - (667, 'Hardcoded string found')
  - (668, 'Hardcoded string found')
  - (671, 'Hardcoded string found')
  - (672, 'Line exceeds 80 characters')
  - (672, 'Hardcoded string found')
  - (673, 'Hardcoded string found')
  - (676, 'Hardcoded string found')
  - (677, 'Line exceeds 80 characters')
  - (677, 'Hardcoded string found')
  - (678, 'Hardcoded string found')
  - (681, 'Hardcoded string found')
  - (682, 'Line exceeds 80 characters')
  - (682, 'Hardcoded string found')
  - (683, 'Hardcoded string found')
  - (686, 'Hardcoded string found')
  - (687, 'Line exceeds 80 characters')
  - (687, 'Hardcoded string found')
  - (688, 'Hardcoded string found')
  - (691, 'Hardcoded string found')
  - (692, 'Line exceeds 80 characters')
  - (692, 'Hardcoded string found')
  - (693, 'Hardcoded string found')
  - (696, 'Hardcoded string found')
  - (697, 'Line exceeds 80 characters')
  - (697, 'Hardcoded string found')
  - (698, 'Hardcoded string found')
  - (701, 'Hardcoded string found')
  - (702, 'Line exceeds 80 characters')
  - (702, 'Hardcoded string found')
  - (703, 'Line exceeds 80 characters')
  - (703, 'Hardcoded string found')
  - (706, 'Hardcoded string found')
  - (707, 'Line exceeds 80 characters')
  - (707, 'Hardcoded string found')
  - (708, 'Hardcoded string found')
  - (711, 'Hardcoded string found')
  - (712, 'Line exceeds 80 characters')
  - (712, 'Hardcoded string found')
  - (713, 'Hardcoded string found')
  - (716, 'Hardcoded string found')
  - (717, 'Line exceeds 80 characters')
  - (717, 'Hardcoded string found')
  - (718, 'Hardcoded string found')
  - (721, 'Hardcoded string found')
  - (722, 'Line exceeds 80 characters')
  - (722, 'Hardcoded string found')
  - (723, 'Hardcoded string found')
  - (726, 'Hardcoded string found')
  - (727, 'Line exceeds 80 characters')
  - (727, 'Hardcoded string found')
  - (732, 'Hardcoded string found')
  - (733, 'Hardcoded string found')
  - (734, 'Line exceeds 80 characters')
  - (734, 'Hardcoded string found')
  - (735, 'Hardcoded string found')
  - (738, 'Hardcoded string found')
  - (739, 'Line exceeds 80 characters')
  - (739, 'Hardcoded string found')
  - (741, 'Line exceeds 80 characters')
  - (741, 'Hardcoded string found')
  - (742, 'Line exceeds 80 characters')
  - (742, 'Hardcoded string found')
  - (744, 'Hardcoded string found')
  - (745, 'Hardcoded string found')
  - (746, 'Hardcoded string found')
  - (747, 'Line exceeds 80 characters')
  - (747, 'Hardcoded string found')
  - (748, 'Hardcoded string found')
  - (754, 'Hardcoded string found')
  - (755, 'Hardcoded string found')
  - (756, 'Hardcoded string found')
  - (762, 'Hardcoded string found')
  - (763, 'Line exceeds 80 characters')
  - (763, 'Hardcoded string found')
  - (764, 'Line exceeds 80 characters')
  - (764, 'Hardcoded string found')
  - (765, 'Hardcoded string found')
  - (767, 'Hardcoded string found')
  - (769, 'Hardcoded string found')
  - (770, 'Hardcoded string found')
  - (771, 'Hardcoded string found')
  - (776, 'Hardcoded string found')
  - (778, 'Hardcoded string found')
  - (779, 'Line exceeds 80 characters')
  - (779, 'Hardcoded string found')
  - (780, 'Line exceeds 80 characters')
  - (780, 'Hardcoded string found')
  - (781, 'Hardcoded string found')
  - (784, 'Hardcoded string found')
  - (786, 'Hardcoded string found')
  - (790, 'Hardcoded string found')
  - (791, 'Line exceeds 80 characters')
  - (791, 'Hardcoded string found')
  - (792, 'Hardcoded string found')
  - (794, 'Hardcoded string found')
  - (795, 'Hardcoded string found')
  - (796, 'Hardcoded string found')
  - (797, 'Line exceeds 80 characters')
  - (797, 'Hardcoded string found')
  - (800, 'Hardcoded string found')
  - (801, 'Line exceeds 80 characters')
  - (801, 'Hardcoded string found')
  - (802, 'Hardcoded string found')
  - (803, 'Hardcoded string found')
  - (808, 'Hardcoded string found')
  - (809, 'Line exceeds 80 characters')
  - (809, 'Hardcoded string found')
  - (810, 'Hardcoded string found')
  - (812, 'Hardcoded string found')
  - (813, 'Hardcoded string found')
  - (814, 'Hardcoded string found')
  - (815, 'Line exceeds 80 characters')
  - (815, 'Hardcoded string found')
  - (816, 'Hardcoded string found')
  - (817, 'Hardcoded string found')
  - (823, 'Hardcoded string found')
  - (824, 'Line exceeds 80 characters')
  - (824, 'Hardcoded string found')
  - (826, 'Hardcoded string found')
  - (827, 'Line exceeds 80 characters')
  - (827, 'Hardcoded string found')
  - (829, 'Hardcoded string found')
  - (830, 'Hardcoded string found')
  - (831, 'Hardcoded string found')
  - (832, 'Line exceeds 80 characters')
  - (832, 'Hardcoded string found')
  - (834, 'Hardcoded string found')
  - (835, 'Hardcoded string found')
  - (836, 'Hardcoded string found')
  - (841, 'Hardcoded string found')
  - (842, 'Line exceeds 80 characters')
  - (842, 'Hardcoded string found')
  - (843, 'Line exceeds 80 characters')
  - (843, 'Hardcoded string found')
  - (844, 'Hardcoded string found')
  - (845, 'Line exceeds 80 characters')
  - (845, 'Hardcoded string found')
  - (846, 'Line exceeds 80 characters')
  - (846, 'Hardcoded string found')
  - (847, 'Hardcoded string found')
  - (853, 'Hardcoded string found')
  - (854, 'Hardcoded string found')
  - (855, 'Hardcoded string found')
  - (857, 'Hardcoded string found')
  - (858, 'Hardcoded string found')
  - (864, 'Hardcoded string found')
  - (865, 'Line exceeds 80 characters')
  - (865, 'Hardcoded string found')
  - (866, 'Line exceeds 80 characters')
  - (866, 'Hardcoded string found')
  - (867, 'Hardcoded string found')
  - (869, 'Hardcoded string found')
  - (871, 'Hardcoded string found')
  - (872, 'Hardcoded string found')
  - (873, 'Hardcoded string found')
  - (874, 'Hardcoded string found')
  - (875, 'Line exceeds 80 characters')
  - (875, 'Hardcoded string found')
  - (879, 'Hardcoded string found')
  - (880, 'Hardcoded string found')
  - (881, 'Line exceeds 80 characters')
  - (881, 'Hardcoded string found')
  - (887, 'Hardcoded string found')
  - (888, 'Line exceeds 80 characters')
  - (888, 'Hardcoded string found')
  - (889, 'Line exceeds 80 characters')
  - (889, 'Hardcoded string found')
  - (890, 'Hardcoded string found')
  - (897, 'Hardcoded string found')
  - (898, 'Line exceeds 80 characters')
  - (898, 'Hardcoded string found')
  - (902, 'Hardcoded string found')
  - (903, 'Hardcoded string found')
  - (904, 'Line exceeds 80 characters')
  - (904, 'Hardcoded string found')
  - (905, 'Line exceeds 80 characters')
  - (905, 'Hardcoded string found')
  - (906, 'Hardcoded string found')
  - (910, 'Hardcoded string found')
  - (911, 'Line exceeds 80 characters')
  - (911, 'Hardcoded string found')
  - (912, 'Line exceeds 80 characters')
  - (912, 'Hardcoded string found')
  - (915, 'Hardcoded string found')
  - (921, 'Hardcoded string found')
  - (922, 'Line exceeds 80 characters')
  - (922, 'Hardcoded string found')
  - (923, 'Line exceeds 80 characters')
  - (923, 'Hardcoded string found')
  - (926, 'Hardcoded string found')
  - (927, 'Line exceeds 80 characters')
  - (927, 'Hardcoded string found')
  - (928, 'Hardcoded string found')
  - (930, 'Hardcoded string found')
  - (931, 'Hardcoded string found')
  - (932, 'Hardcoded string found')
  - (933, 'Line exceeds 80 characters')
  - (933, 'Hardcoded string found')
  - (934, 'Hardcoded string found')
  - (939, 'Hardcoded string found')
  - (940, 'Line exceeds 80 characters')
  - (940, 'Hardcoded string found')
  - (941, 'Hardcoded string found')
  - (942, 'Hardcoded string found')
  - (943, 'Hardcoded string found')
  - (946, 'Hardcoded string found')
  - (947, 'Hardcoded string found')
  - (948, 'Hardcoded string found')
  - (950, 'Line exceeds 80 characters')
  - (950, 'Hardcoded string found')
  - (951, 'Line exceeds 80 characters')
  - (951, 'Hardcoded string found')
  - (953, 'Hardcoded string found')
  - (954, 'Hardcoded string found')
  - (955, 'Hardcoded string found')
  - (956, 'Line exceeds 80 characters')
  - (956, 'Hardcoded string found')
  - (959, 'Hardcoded string found')
  - (960, 'Line exceeds 80 characters')
  - (960, 'Hardcoded string found')
  - (962, 'Hardcoded string found')
  - (966, 'Hardcoded string found')
  - (967, 'Line exceeds 80 characters')
  - (967, 'Hardcoded string found')
  - (968, 'Hardcoded string found')
  - (971, 'Hardcoded string found')
  - (972, 'Line exceeds 80 characters')
  - (972, 'Hardcoded string found')
  - (974, 'Line exceeds 80 characters')
  - (974, 'Hardcoded string found')
  - (977, 'Hardcoded string found')
  - (978, 'Line exceeds 80 characters')
  - (978, 'Hardcoded string found')
  - (979, 'Line exceeds 80 characters')
  - (979, 'Hardcoded string found')
  - (980, 'Hardcoded string found')
  - (981, 'Line exceeds 80 characters')
  - (981, 'Hardcoded string found')
  - (982, 'Line exceeds 80 characters')
  - (982, 'Hardcoded string found')
  - (983, 'Hardcoded string found')
  - (984, 'Hardcoded string found')
  - (989, 'Hardcoded string found')
  - (990, 'Hardcoded string found')
  - (991, 'Hardcoded string found')
  - (992, 'Line exceeds 80 characters')
  - (992, 'Hardcoded string found')
  - (993, 'Hardcoded string found')
  - (994, 'Hardcoded string found')
  - (995, 'Line exceeds 80 characters')
  - (995, 'Hardcoded string found')
  - (998, 'Hardcoded string found')

**Comment by Zeusofsky** [comment]
I got it.
