### ISSUE TITLE
Issue-Adds solana wallet adapter (#39)

* feat: adds solana wallet adapter

* feat: cleaning up dependencies

* fix: fixes code as per pr review comments

* fix: fixes styling for dapp buttons

* fix: unused fragment

* fix: pr comments

### ISSUE THREAD

**Issue by kazupot7** [kazupot7/token-creator#160]
Automated Review Comments
Issues in package.json:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (17, 'Line exceeds 80 characters')
  - (19, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
  - (42, 'Hardcoded string found')
  - (44, 'Hardcoded string found')
  - (45, 'Hardcoded string found')
  - (46, 'Hardcoded string found')
  - (47, 'Hardcoded string found')
  - (48, 'Hardcoded string found')
  - (51, 'Line exceeds 80 characters')
  - (53, 'Hardcoded string found')
  - (54, 'Hardcoded string found')
  - (57, 'Hardcoded string found')
  - (66, 'Hardcoded string found')
  - (68, 'Hardcoded string found')
  - (69, 'Hardcoded string found')
  - (74, 'Hardcoded string found')
  - (75, 'Hardcoded string found')
  - (76, 'Hardcoded string found')
  - (78, 'Hardcoded string found')
  - (79, 'Hardcoded string found')
  - (90, 'Hardcoded string found')
  - (92, 'Hardcoded string found')
  - (93, 'Hardcoded string found')
  - (94, 'Line exceeds 80 characters')
  - (96, 'Hardcoded string found')
Issues in src/components/AppBar/index.tsx:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (25, 'Hardcoded string found')
  - (26, 'Hardcoded string found')
  - (31, 'Hardcoded string found')
  - (33, 'Hardcoded string found')
  - (35, 'Hardcoded string found')
Issues in src/components/ConnectButton/index.tsx:
  - (4, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (24, 'Line exceeds 80 characters')
Issues in src/components/CurrentUserBadge/index.tsx:
  - (2, 'Hardcoded string found')
  - (30, 'Hardcoded string found')
Issues in src/components/Layout/index.tsx:
  - (1, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
Issues in src/components/Settings/index.tsx:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
Issues in src/constants/labels.ts:
  - (3, 'Line exceeds 80 characters')
  - (5, 'Line exceeds 80 characters')
  - (7, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
Issues in src/contexts/accounts.tsx:
  - (2, 'Hardcoded string found')
Issues in src/contexts/connection.tsx:
  - (9, 'Line exceeds 80 characters')
  - (9, 'Hardcoded string found')
  - (15, 'Line exceeds 80 characters')
  - (20, 'Line exceeds 80 characters')
  - (21, 'Line exceeds 80 characters')
  - (29, 'Line exceeds 80 characters')
Issues in src/routes.tsx:
  - (3, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (30, 'TODO found')
  - (32, 'Line exceeds 80 characters')
Issues in src/views/faucet/index.tsx:
  - (2, 'Hardcoded string found')
  - (29, 'Hardcoded string found')
  - (35, 'Hardcoded string found')
  - (46, 'Hardcoded string found')
  - (47, 'Hardcoded string found')
Issues in src/views/home/index.tsx:
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
  - (25, 'Line exceeds 80 characters')
  - (29, 'Hardcoded string found')
  - (37, 'Hardcoded string found')
Issues in yarn.lock:
  - (2, 'Hardcoded string found')
  - (7, 'Line exceeds 80 characters')
  - (8, 'Line exceeds 80 characters')
  - (10, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (17, 'Line exceeds 80 characters')
  - (18, 'Line exceeds 80 characters')
  - (22, 'Line exceeds 80 characters')
  - (23, 'Line exceeds 80 characters')
  - (25, 'Hardcoded string found')
  - (26, 'Hardcoded string found')
  - (27, 'Hardcoded string found')
  - (28, 'Hardcoded string found')
  - (32, 'Line exceeds 80 characters')
  - (33, 'Line exceeds 80 characters')
  - (35, 'Hardcoded string found')
  - (36, 'Hardcoded string found')
  - (41, 'Line exceeds 80 characters')
  - (42, 'Line exceeds 80 characters')
  - (45, 'Line exceeds 80 characters')
  - (46, 'Line exceeds 80 characters')
  - (48, 'Hardcoded string found')
  - (49, 'Hardcoded string found')
  - (55, 'Line exceeds 80 characters')
  - (56, 'Line exceeds 80 characters')
  - (60, 'Line exceeds 80 characters')
  - (61, 'Line exceeds 80 characters')
  - (63, 'Hardcoded string found')
  - (64, 'Hardcoded string found')
  - (65, 'Hardcoded string found')
  - (66, 'Hardcoded string found')
  - (70, 'Line exceeds 80 characters')
  - (71, 'Line exceeds 80 characters')
  - (73, 'Hardcoded string found')
  - (74, 'Hardcoded string found')
  - (79, 'Line exceeds 80 characters')
  - (80, 'Line exceeds 80 characters')
  - (90, 'Line exceeds 80 characters')
  - (91, 'Line exceeds 80 characters')
  - (98, 'Line exceeds 80 characters')
  - (105, 'Line exceeds 80 characters')
  - (106, 'Line exceeds 80 characters')
  - (110, 'Line exceeds 80 characters')
  - (111, 'Line exceeds 80 characters')
  - (117, 'Line exceeds 80 characters')
  - (118, 'Line exceeds 80 characters')
  - (120, 'Hardcoded string found')
  - (121, 'Hardcoded string found')
  - (125, 'Line exceeds 80 characters')
  - (126, 'Line exceeds 80 characters')
  - (130, 'Line exceeds 80 characters')
  - (131, 'Line exceeds 80 characters')
  - (135, 'Line exceeds 80 characters')
  - (136, 'Line exceeds 80 characters')
  - (140, 'Line exceeds 80 characters')
  - (141, 'Line exceeds 80 characters')
  - (145, 'Line exceeds 80 characters')
  - (146, 'Line exceeds 80 characters')
  - (148, 'Hardcoded string found')
  - (152, 'Line exceeds 80 characters')
  - (153, 'Line exceeds 80 characters')
  - (157, 'Line exceeds 80 characters')
  - (158, 'Line exceeds 80 characters')
  - (160, 'Hardcoded string found')
  - (161, 'Hardcoded string found')
  - (162, 'Hardcoded string found')
  - (166, 'Line exceeds 80 characters')
  - (167, 'Line exceeds 80 characters')
  - (169, 'Hardcoded string found')
  - (170, 'Hardcoded string found')
  - (171, 'Hardcoded string found')
  - (172, 'Hardcoded string found')
  - (173, 'Hardcoded string found')
  - (174, 'Hardcoded string found')
  - (175, 'Hardcoded string found')
  - (179, 'Line exceeds 80 characters')
  - (181, 'Hardcoded string found')
  - (182, 'Hardcoded string found')
  - (186, 'Line exceeds 80 characters')
  - (187, 'Line exceeds 80 characters')
  - (198, 'Line exceeds 80 characters')
  - (199, 'Line exceeds 80 characters')
  - (205, 'Line exceeds 80 characters')
  - (206, 'Line exceeds 80 characters')
  - (208, 'Hardcoded string found')
  - (212, 'Line exceeds 80 characters')
  - (213, 'Line exceeds 80 characters')
  - (215, 'Hardcoded string found')
  - (223, 'Line exceeds 80 characters')
  - (224, 'Line exceeds 80 characters')
  - (232, 'Line exceeds 80 characters')
  - (233, 'Line exceeds 80 characters')
  - (235, 'Hardcoded string found')
  - (236, 'Hardcoded string found')
  - (237, 'Hardcoded string found')
  - (238, 'Hardcoded string found')
  - (244, 'Line exceeds 80 characters')
  - (245, 'Line exceeds 80 characters')
  - (249, 'Line exceeds 80 characters')
  - (251, 'Line exceeds 80 characters')
  - (252, 'Line exceeds 80 characters')
  - (256, 'Line exceeds 80 characters')
  - (257, 'Line exceeds 80 characters')
  - (259, 'Hardcoded string found')
  - (260, 'Hardcoded string found')
  - (264, 'Line exceeds 80 characters')
  - (265, 'Line exceeds 80 characters')
  - (268, 'Line exceeds 80 characters')
  - (269, 'Line exceeds 80 characters')
  - (271, 'Hardcoded string found')
  - (274, 'Line exceeds 80 characters')
  - (275, 'Line exceeds 80 characters')
  - (279, 'Line exceeds 80 characters')
  - (280, 'Line exceeds 80 characters')
  - (284, 'Line exceeds 80 characters')
  - (286, 'Line exceeds 80 characters')
  - (287, 'Line exceeds 80 characters')
  - (291, 'Line exceeds 80 characters')
  - (292, 'Line exceeds 80 characters')
  - (296, 'Line exceeds 80 characters')
  - (303, 'Line exceeds 80 characters')
  - (310, 'Line exceeds 80 characters')
  - (312, 'Line exceeds 80 characters')
  - (313, 'Line exceeds 80 characters')
  - (317, 'Line exceeds 80 characters')
  - (318, 'Line exceeds 80 characters')
  - (322, 'Line exceeds 80 characters')
  - (330, 'Line exceeds 80 characters')
  - (339, 'Line exceeds 80 characters')
  - (340, 'Line exceeds 80 characters')
  - (342, 'Line exceeds 80 characters')
  - (347, 'Line exceeds 80 characters')
  - (348, 'Line exceeds 80 characters')
  - (352, 'Line exceeds 80 characters')
  - (354, 'Line exceeds 80 characters')
  - (355, 'Line exceeds 80 characters')
  - (359, 'Line exceeds 80 characters')
  - (368, 'Line exceeds 80 characters')
  - (375, 'Line exceeds 80 characters')
  - (376, 'Line exceeds 80 characters')
  - (388, 'Line exceeds 80 characters')
  - (390, 'Line exceeds 80 characters')
  - (396, 'Line exceeds 80 characters')
  - (397, 'Line exceeds 80 characters')
  - (405, 'Line exceeds 80 characters')
  - (406, 'Line exceeds 80 characters')
  - (407, 'Line exceeds 80 characters')
  - (408, 'Line exceeds 80 characters')
  - (409, 'Line exceeds 80 characters')
  - (414, 'Line exceeds 80 characters')
  - (415, 'Line exceeds 80 characters')
  - (419, 'Line exceeds 80 characters')
  - (420, 'Line exceeds 80 characters')
  - (424, 'Line exceeds 80 characters')
  - (426, 'Line exceeds 80 characters')
  - (431, 'Line exceeds 80 characters')
  - (432, 'Line exceeds 80 characters')
  - (436, 'Line exceeds 80 characters')
  - (444, 'Line exceeds 80 characters')
  - (447, 'Line exceeds 80 characters')
  - (453, 'Line exceeds 80 characters')
  - (454, 'Line exceeds 80 characters')
  - (456, 'Line exceeds 80 characters')
  - (457, 'Line exceeds 80 characters')
  - (461, 'Line exceeds 80 characters')
  - (462, 'Line exceeds 80 characters')
  - (466, 'Line exceeds 80 characters')
  - (474, 'Line exceeds 80 characters')
  - (475, 'Line exceeds 80 characters')
  - (481, 'Line exceeds 80 characters')
  - (482, 'Line exceeds 80 characters')
  - (489, 'Line exceeds 80 characters')
  - (490, 'Line exceeds 80 characters')
  - (503, 'Line exceeds 80 characters')
  - (505, 'Line exceeds 80 characters')
  - (506, 'Line exceeds 80 characters')
  - (510, 'Line exceeds 80 characters')
  - (511, 'Line exceeds 80 characters')
  - (514, 'Line exceeds 80 characters')
  - (515, 'Line exceeds 80 characters')

**Comment by Zeusofsky** [comment]
I got it.
