### ISSUE TITLE
Issue-Added accountError example

### ISSUE THREAD

**Issue by kazupot7** [kazupot7/token-creator#173]
Automated Review Comments
Issues in package.json:
  - (3, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
Issues in src/components/CreateAccountError.tsx:
  - (2, 'Hardcoded string found')
  - (23, 'Line exceeds 80 characters')
  - (27, 'Line exceeds 80 characters')
  - (35, 'Line exceeds 80 characters')
Issues in src/views/home/index.tsx:
  - (1, 'Line exceeds 80 characters')
  - (14, 'Line exceeds 80 characters')

**Comment by Zeusofsky** [comment]
I got it.
