### ISSUE TITLE
Issue-fix: connections

### ISSUE THREAD

**Issue by kazupot7** [kazupot7/token-creator#18]
Automated Review Comments
Issues in README.md:
  - (8, 'Line exceeds 80 characters')
  - (39, 'Line exceeds 80 characters')
  - (40, 'Line exceeds 80 characters')
Issues in public/index.html:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (9, 'Line exceeds 80 characters')
Issues in src/components/Layout/index.tsx:
  - (2, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
Issues in src/config/tokens.json:
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Line exceeds 80 characters')
  - (7, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (14, 'Line exceeds 80 characters')
  - (14, 'Hardcoded string found')
Issues in src/contexts/accounts.tsx:
  - (2, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
Issues in src/contexts/connection.tsx:
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (21, 'Line exceeds 80 characters')
  - (25, 'Line exceeds 80 characters')
  - (26, 'Line exceeds 80 characters')
Issues in src/contexts/market.tsx:
  - (2, 'Hardcoded string found')
Issues in src/contexts/wallet.tsx:
  - (7, 'Line exceeds 80 characters')
  - (10, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (25, 'Hardcoded string found')
  - (32, 'Hardcoded string found')
  - (39, 'Hardcoded string found')
Issues in src/index.css:
  - (2, 'Hardcoded string found')
Issues in src/manifest.json:
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
Issues in src/views/faucet/index.tsx:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (27, 'Hardcoded string found')
  - (29, 'Hardcoded string found')
  - (30, 'Hardcoded string found')
  - (35, 'Hardcoded string found')
  - (39, 'Hardcoded string found')
  - (42, 'Hardcoded string found')
  - (43, 'Hardcoded string found')
  - (45, 'Hardcoded string found')
  - (51, 'Hardcoded string found')
  - (55, 'Hardcoded string found')
Issues in src/views/home/index.tsx:
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (16, 'Line exceeds 80 characters')
  - (30, 'Hardcoded string found')
  - (44, 'Hardcoded string found')
  - (45, 'TODO found')

**Comment by christianagalindo7** [comment]
I got it.
