### ISSUE TITLE
Issue-Update test token metadata

### ISSUE THREAD

**Issue by kazupot7** [kazupot7/token-creator#191]
Automated Review Comments
Issues in public/token_metadata.json:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Line exceeds 80 characters')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')

**Comment by billmbowling3** [comment]
I got it.
