### ISSUE TITLE
Issue-Add documentation

### ISSUE THREAD

**Issue by kazupot7** [kazupot7/token-creator#195]
Automated Review Comments
Issues in README.md:
  - (5, 'Line exceeds 80 characters')
  - (13, 'Line exceeds 80 characters')
  - (15, 'Line exceeds 80 characters')
  - (48, 'Line exceeds 80 characters')
  - (108, 'Line exceeds 80 characters')
  - (111, 'Line exceeds 80 characters')
  - (113, 'Line exceeds 80 characters')
  - (115, 'Line exceeds 80 characters')
  - (140, 'Line exceeds 80 characters')
  - (143, 'Line exceeds 80 characters')
  - (155, 'Hardcoded string found')
  - (156, 'Hardcoded string found')
  - (157, 'Hardcoded string found')
  - (161, 'Line exceeds 80 characters')
  - (166, 'Line exceeds 80 characters')
  - (168, 'Line exceeds 80 characters')
  - (187, 'Line exceeds 80 characters')
  - (188, 'Line exceeds 80 characters')
  - (188, 'Hardcoded string found')
  - (190, 'Line exceeds 80 characters')
  - (193, 'Line exceeds 80 characters')
  - (194, 'Line exceeds 80 characters')
  - (237, 'Line exceeds 80 characters')
  - (241, 'Line exceeds 80 characters')
  - (243, 'Line exceeds 80 characters')
  - (249, 'Line exceeds 80 characters')
  - (260, 'Hardcoded string found')
  - (263, 'Line exceeds 80 characters')
  - (271, 'Line exceeds 80 characters')
  - (274, 'Line exceeds 80 characters')
  - (278, 'Line exceeds 80 characters')
  - (280, 'Line exceeds 80 characters')

**Comment by martinjbrown776** [comment]
I got it.
