### ISSUE TITLE
Issue-Feat: add tab for getting token metadata

### ISSUE THREAD

**Issue by kazupot7** [kazupot7/token-creator#197]
Automated Review Comments
Issues in src/components/AppBar.tsx:
  - (7, 'Hardcoded string found')
  - (9, 'Line exceeds 80 characters')
  - (9, 'Hardcoded string found')
Issues in src/components/GetMetadata.tsx:
  - (2, 'Hardcoded string found')
  - (33, 'Hardcoded string found')
  - (35, 'Line exceeds 80 characters')
  - (36, 'Hardcoded string found')
  - (40, 'Line exceeds 80 characters')
  - (58, 'Line exceeds 80 characters')
  - (62, 'Line exceeds 80 characters')
  - (63, 'Line exceeds 80 characters')
  - (63, 'Hardcoded string found')
  - (66, 'Line exceeds 80 characters')
  - (70, 'Line exceeds 80 characters')
  - (74, 'Line exceeds 80 characters')
  - (78, 'Line exceeds 80 characters')
  - (79, 'Hardcoded string found')
  - (82, 'Line exceeds 80 characters')
  - (86, 'Line exceeds 80 characters')
  - (87, 'Line exceeds 80 characters')
Issues in src/pages/metadata.tsx:
  - (2, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
Issues in src/views/metadata/index.tsx:
  - (3, 'Hardcoded string found')
  - (12, 'Line exceeds 80 characters')

**Comment by brandonabeal110** [comment]
I got it.
