### ISSUE TITLE
Issue-Clean up form input and fix image display

### ISSUE THREAD

**Issue by kazupot7** [kazupot7/token-creator#201]
Automated Review Comments
Issues in src/components/GetMetadata.tsx:
  - (12, 'Line exceeds 80 characters')
  - (13, 'Line exceeds 80 characters')
  - (13, 'Hardcoded string found')
  - (14, 'Line exceeds 80 characters')
  - (14, 'Hardcoded string found')
  - (17, 'Line exceeds 80 characters')

**Comment by williamddobson3** [comment]
I got it.
