### ISSUE TITLE
Issue-Feat: add tab for uploading via bundlr

### ISSUE THREAD

**Issue by kazupot7** [kazupot7/token-creator#203]
Automated Review Comments
Issues in package.json:
  - (2, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (25, 'Hardcoded string found')
  - (27, 'Hardcoded string found')
Issues in src/components/AppBar.tsx:
  - (2, 'Hardcoded string found')
  - (18, 'Line exceeds 80 characters')
  - (22, 'Line exceeds 80 characters')
  - (22, 'Hardcoded string found')
  - (24, 'Line exceeds 80 characters')
  - (25, 'Line exceeds 80 characters')
  - (25, 'Hardcoded string found')
  - (26, 'Line exceeds 80 characters')
  - (26, 'Hardcoded string found')
  - (27, 'Line exceeds 80 characters')
  - (27, 'Hardcoded string found')
  - (28, 'Line exceeds 80 characters')
  - (28, 'Hardcoded string found')
  - (29, 'Line exceeds 80 characters')
  - (29, 'Hardcoded string found')
  - (30, 'Line exceeds 80 characters')
  - (30, 'Hardcoded string found')
  - (31, 'Line exceeds 80 characters')
  - (38, 'Hardcoded string found')
  - (42, 'Line exceeds 80 characters')
  - (46, 'Line exceeds 80 characters')
  - (47, 'Hardcoded string found')
  - (50, 'Line exceeds 80 characters')
  - (51, 'Hardcoded string found')
  - (54, 'Line exceeds 80 characters')
  - (55, 'Hardcoded string found')
  - (58, 'Line exceeds 80 characters')
  - (59, 'Hardcoded string found')
  - (62, 'Line exceeds 80 characters')
  - (63, 'Hardcoded string found')
  - (66, 'Line exceeds 80 characters')
  - (67, 'Hardcoded string found')
  - (71, 'Line exceeds 80 characters')
  - (71, 'Hardcoded string found')
  - (84, 'Hardcoded string found')
  - (93, 'Hardcoded string found')
  - (95, 'Hardcoded string found')
  - (106, 'Hardcoded string found')
  - (108, 'Line exceeds 80 characters')
  - (108, 'Hardcoded string found')
  - (109, 'Line exceeds 80 characters')
  - (109, 'Hardcoded string found')
  - (110, 'Line exceeds 80 characters')
  - (110, 'Hardcoded string found')
  - (121, 'Hardcoded string found')
  - (126, 'Hardcoded string found')
  - (128, 'Hardcoded string found')
  - (130, 'Hardcoded string found')
  - (131, 'Hardcoded string found')
  - (133, 'Line exceeds 80 characters')
  - (136, 'Hardcoded string found')
  - (137, 'Hardcoded string found')
  - (143, 'Line exceeds 80 characters')
  - (146, 'Line exceeds 80 characters')
  - (153, 'Line exceeds 80 characters')
  - (153, 'Hardcoded string found')
  - (155, 'Hardcoded string found')
  - (158, 'Hardcoded string found')
Issues in src/components/Notification.tsx:
  - (1, 'Line exceeds 80 characters')
  - (5, 'Line exceeds 80 characters')
  - (6, 'Line exceeds 80 characters')
  - (12, 'Hardcoded string found')
  - (16, 'Line exceeds 80 characters')
  - (16, 'Hardcoded string found')
  - (17, 'Line exceeds 80 characters')
  - (17, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
Issues in src/components/UploadMetadata.tsx:
  - (2, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (40, 'Hardcoded string found')
  - (50, 'Hardcoded string found')
  - (57, 'Hardcoded string found')
  - (66, 'Hardcoded string found')
  - (68, 'Hardcoded string found')
  - (74, 'Hardcoded string found')
  - (79, 'Hardcoded string found')
  - (84, 'Hardcoded string found')
  - (120, 'Hardcoded string found')
  - (136, 'Line exceeds 80 characters')
  - (144, 'Hardcoded string found')
  - (178, 'Line exceeds 80 characters')
  - (186, 'Line exceeds 80 characters')
  - (193, 'Hardcoded string found')
  - (216, 'Line exceeds 80 characters')
  - (217, 'Line exceeds 80 characters')
  - (217, 'Hardcoded string found')
  - (218, 'Line exceeds 80 characters')
  - (219, 'Line exceeds 80 characters')
  - (219, 'Hardcoded string found')
  - (229, 'Line exceeds 80 characters')
  - (235, 'Line exceeds 80 characters')
  - (236, 'Line exceeds 80 characters')
  - (243, 'Line exceeds 80 characters')
  - (243, 'Hardcoded string found')
  - (250, 'Line exceeds 80 characters')
  - (251, 'Line exceeds 80 characters')
  - (254, 'Line exceeds 80 characters')
  - (254, 'Hardcoded string found')
  - (272, 'Line exceeds 80 characters')
  - (279, 'Hardcoded string found')
  - (291, 'Hardcoded string found')
  - (292, 'Line exceeds 80 characters')
  - (292, 'Hardcoded string found')
  - (293, 'Line exceeds 80 characters')
  - (301, 'Line exceeds 80 characters')
  - (305, 'Hardcoded string found')
  - (306, 'Hardcoded string found')
  - (308, 'Hardcoded string found')
  - (310, 'Line exceeds 80 characters')
  - (312, 'Hardcoded string found')
  - (313, 'Hardcoded string found')
  - (319, 'Line exceeds 80 characters')
  - (324, 'Hardcoded string found')
  - (339, 'Hardcoded string found')
  - (349, 'Line exceeds 80 characters')
  - (358, 'Hardcoded string found')
  - (378, 'Line exceeds 80 characters')
  - (382, 'Hardcoded string found')
  - (383, 'Hardcoded string found')
  - (385, 'Hardcoded string found')
  - (387, 'Line exceeds 80 characters')
  - (389, 'Hardcoded string found')
  - (390, 'Hardcoded string found')
  - (396, 'Line exceeds 80 characters')
  - (401, 'Hardcoded string found')
  - (416, 'Hardcoded string found')
  - (426, 'Line exceeds 80 characters')
Issues in src/pages/uploader.tsx:
  - (2, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
Issues in src/views/uploader/index.tsx:
  - (2, 'Hardcoded string found')
  - (12, 'Line exceeds 80 characters')

**Comment by martinjbrown776** [comment]
I got it.
