### ISSUE TITLE
Issue-feat: 1 transaction create token

### ISSUE THREAD

**Issue by kazupot7** [kazupot7/token-creator#208]
Automated Review Comments
Issues in package.json:
  - (17, 'Hardcoded string found')
Issues in src/components/CreateToken.tsx:
  - (1, 'Hardcoded string found')
  - (4, 'Line exceeds 80 characters')
  - (5, 'Line exceeds 80 characters')
  - (6, 'Line exceeds 80 characters')
  - (17, 'Line exceeds 80 characters')
  - (66, 'Line exceeds 80 characters')
  - (69, 'Line exceeds 80 characters')
Issues in yarn.lock:
  - (7, 'Line exceeds 80 characters')
  - (8, 'Line exceeds 80 characters')
  - (10, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (16, 'Line exceeds 80 characters')
  - (17, 'Line exceeds 80 characters')
  - (19, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (25, 'Line exceeds 80 characters')
  - (26, 'Line exceeds 80 characters')
  - (32, 'Line exceeds 80 characters')
  - (33, 'Line exceeds 80 characters')
  - (35, 'Hardcoded string found')
  - (36, 'Hardcoded string found')
  - (37, 'Hardcoded string found')
  - (38, 'Hardcoded string found')
  - (39, 'Hardcoded string found')
  - (44, 'Line exceeds 80 characters')
  - (45, 'Line exceeds 80 characters')
  - (47, 'Hardcoded string found')
  - (48, 'Hardcoded string found')
  - (49, 'Hardcoded string found')
  - (50, 'Hardcoded string found')
  - (51, 'Hardcoded string found')
  - (52, 'Hardcoded string found')
  - (53, 'Hardcoded string found')
  - (58, 'Line exceeds 80 characters')
  - (59, 'Line exceeds 80 characters')
  - (61, 'Hardcoded string found')
  - (62, 'Hardcoded string found')
  - (67, 'Line exceeds 80 characters')
  - (68, 'Line exceeds 80 characters')
  - (70, 'Hardcoded string found')
  - (71, 'Hardcoded string found')
  - (76, 'Line exceeds 80 characters')
  - (77, 'Line exceeds 80 characters')
  - (83, 'Line exceeds 80 characters')
  - (84, 'Line exceeds 80 characters')
  - (86, 'Hardcoded string found')
  - (87, 'Hardcoded string found')
  - (92, 'Line exceeds 80 characters')
  - (93, 'Line exceeds 80 characters')
  - (95, 'Hardcoded string found')
  - (100, 'Line exceeds 80 characters')
  - (101, 'Line exceeds 80 characters')
  - (103, 'Hardcoded string found')
  - (108, 'Line exceeds 80 characters')
  - (109, 'Line exceeds 80 characters')
  - (115, 'Line exceeds 80 characters')
  - (116, 'Line exceeds 80 characters')
  - (118, 'Hardcoded string found')
  - (119, 'Hardcoded string found')
  - (120, 'Hardcoded string found')
  - (121, 'Hardcoded string found')
  - (122, 'Hardcoded string found')
  - (123, 'Hardcoded string found')
  - (124, 'Hardcoded string found')
  - (125, 'Hardcoded string found')
  - (126, 'Hardcoded string found')
  - (127, 'Hardcoded string found')
  - (128, 'Hardcoded string found')
  - (129, 'Hardcoded string found')
  - (130, 'Hardcoded string found')
  - (131, 'Hardcoded string found')
  - (132, 'Hardcoded string found')
  - (133, 'Hardcoded string found')
  - (134, 'Hardcoded string found')
  - (135, 'Hardcoded string found')
  - (136, 'Hardcoded string found')
  - (137, 'Hardcoded string found')
  - (138, 'Hardcoded string found')
  - (139, 'Hardcoded string found')
  - (140, 'Hardcoded string found')
  - (141, 'Hardcoded string found')
  - (142, 'Hardcoded string found')
  - (143, 'Hardcoded string found')
  - (144, 'Hardcoded string found')
  - (145, 'Hardcoded string found')
  - (146, 'Hardcoded string found')
  - (147, 'Hardcoded string found')
  - (148, 'Hardcoded string found')
  - (149, 'Hardcoded string found')
  - (150, 'Hardcoded string found')
  - (151, 'Hardcoded string found')
  - (152, 'Hardcoded string found')
  - (153, 'Hardcoded string found')
  - (154, 'Hardcoded string found')
  - (155, 'Hardcoded string found')
  - (156, 'Hardcoded string found')
  - (157, 'Hardcoded string found')
  - (158, 'Hardcoded string found')
  - (159, 'Hardcoded string found')
  - (160, 'Hardcoded string found')
  - (161, 'Hardcoded string found')
  - (162, 'Hardcoded string found')
  - (163, 'Hardcoded string found')
  - (164, 'Hardcoded string found')
  - (165, 'Hardcoded string found')
  - (166, 'Hardcoded string found')
  - (167, 'Hardcoded string found')
  - (168, 'Hardcoded string found')
  - (175, 'Line exceeds 80 characters')
  - (176, 'Line exceeds 80 characters')
  - (178, 'Hardcoded string found')
  - (179, 'Hardcoded string found')
  - (180, 'Hardcoded string found')
  - (181, 'Hardcoded string found')
  - (182, 'Hardcoded string found')
  - (183, 'Hardcoded string found')
  - (184, 'Hardcoded string found')
  - (185, 'Hardcoded string found')
  - (186, 'Hardcoded string found')
  - (187, 'Hardcoded string found')
  - (188, 'Hardcoded string found')
  - (189, 'Hardcoded string found')
  - (190, 'Hardcoded string found')
  - (191, 'Hardcoded string found')
  - (192, 'Hardcoded string found')
  - (193, 'Hardcoded string found')
  - (194, 'Hardcoded string found')
  - (195, 'Hardcoded string found')
  - (196, 'Hardcoded string found')
  - (197, 'Hardcoded string found')
  - (198, 'Hardcoded string found')
  - (199, 'Hardcoded string found')
  - (200, 'Hardcoded string found')
  - (201, 'Hardcoded string found')
  - (202, 'Hardcoded string found')
  - (203, 'Hardcoded string found')
  - (204, 'Hardcoded string found')
  - (205, 'Hardcoded string found')
  - (206, 'Hardcoded string found')
  - (207, 'Hardcoded string found')
  - (212, 'Line exceeds 80 characters')
  - (213, 'Line exceeds 80 characters')
  - (215, 'Hardcoded string found')
  - (216, 'Hardcoded string found')
  - (217, 'Hardcoded string found')
  - (218, 'Hardcoded string found')
  - (219, 'Hardcoded string found')
  - (220, 'Hardcoded string found')
  - (221, 'Hardcoded string found')
  - (222, 'Hardcoded string found')
  - (223, 'Hardcoded string found')
  - (224, 'Hardcoded string found')
  - (225, 'Hardcoded string found')
  - (226, 'Hardcoded string found')
  - (227, 'Hardcoded string found')
  - (228, 'Hardcoded string found')
  - (229, 'Hardcoded string found')
  - (230, 'Hardcoded string found')
  - (231, 'Hardcoded string found')
  - (232, 'Hardcoded string found')
  - (233, 'Hardcoded string found')
  - (234, 'Hardcoded string found')
  - (235, 'Hardcoded string found')
  - (236, 'Hardcoded string found')
  - (237, 'Hardcoded string found')
  - (238, 'Hardcoded string found')
  - (239, 'Hardcoded string found')
  - (240, 'Hardcoded string found')
  - (241, 'Hardcoded string found')
  - (242, 'Hardcoded string found')
  - (243, 'Hardcoded string found')
  - (244, 'Hardcoded string found')
  - (245, 'Hardcoded string found')
  - (246, 'Hardcoded string found')
  - (247, 'Hardcoded string found')
  - (254, 'Line exceeds 80 characters')
  - (255, 'Line exceeds 80 characters')
  - (257, 'Hardcoded string found')
  - (258, 'Hardcoded string found')
  - (259, 'Hardcoded string found')
  - (260, 'Hardcoded string found')
  - (265, 'Line exceeds 80 characters')
  - (266, 'Line exceeds 80 characters')
  - (268, 'Hardcoded string found')
  - (269, 'Hardcoded string found')
  - (274, 'Line exceeds 80 characters')
  - (275, 'Line exceeds 80 characters')
  - (277, 'Hardcoded string found')
  - (278, 'Hardcoded string found')
  - (279, 'Hardcoded string found')
  - (280, 'Hardcoded string found')
  - (285, 'Line exceeds 80 characters')
  - (286, 'Line exceeds 80 characters')
  - (288, 'Hardcoded string found')
  - (289, 'Hardcoded string found')
  - (290, 'Hardcoded string found')
  - (291, 'Hardcoded string found')
  - (292, 'Hardcoded string found')
  - (293, 'Hardcoded string found')
  - (294, 'Hardcoded string found')
  - (299, 'Line exceeds 80 characters')
  - (300, 'Line exceeds 80 characters')
  - (302, 'Hardcoded string found')
  - (303, 'Hardcoded string found')
  - (304, 'Hardcoded string found')
  - (305, 'Hardcoded string found')
  - (306, 'Hardcoded string found')
  - (307, 'Hardcoded string found')
  - (308, 'Hardcoded string found')
  - (309, 'Hardcoded string found')
  - (310, 'Hardcoded string found')
  - (315, 'Line exceeds 80 characters')
  - (316, 'Line exceeds 80 characters')
  - (318, 'Hardcoded string found')
  - (319, 'Hardcoded string found')
  - (320, 'Hardcoded string found')
  - (325, 'Line exceeds 80 characters')
  - (326, 'Line exceeds 80 characters')
  - (328, 'Hardcoded string found')
  - (329, 'Hardcoded string found')
  - (330, 'Hardcoded string found')
  - (331, 'Hardcoded string found')
  - (336, 'Line exceeds 80 characters')
  - (337, 'Line exceeds 80 characters')
  - (339, 'Hardcoded string found')
  - (340, 'Hardcoded string found')
  - (345, 'Line exceeds 80 characters')
  - (346, 'Line exceeds 80 characters')
  - (348, 'Hardcoded string found')
  - (349, 'Hardcoded string found')
  - (350, 'Hardcoded string found')
  - (355, 'Line exceeds 80 characters')
  - (356, 'Line exceeds 80 characters')
  - (358, 'Hardcoded string found')
  - (359, 'Hardcoded string found')
  - (360, 'Hardcoded string found')
  - (365, 'Line exceeds 80 characters')
  - (366, 'Line exceeds 80 characters')
  - (368, 'Hardcoded string found')
  - (373, 'Line exceeds 80 characters')
  - (374, 'Line exceeds 80 characters')
  - (376, 'Hardcoded string found')
  - (377, 'Hardcoded string found')
  - (378, 'Hardcoded string found')
  - (383, 'Line exceeds 80 characters')
  - (384, 'Line exceeds 80 characters')
  - (386, 'Hardcoded string found')
  - (387, 'Hardcoded string found')
  - (392, 'Line exceeds 80 characters')
  - (393, 'Line exceeds 80 characters')
  - (395, 'Hardcoded string found')
  - (396, 'Hardcoded string found')
  - (397, 'Hardcoded string found')
  - (398, 'Hardcoded string found')
  - (403, 'Line exceeds 80 characters')
  - (404, 'Line exceeds 80 characters')
  - (406, 'Hardcoded string found')
  - (407, 'Hardcoded string found')
  - (408, 'Hardcoded string found')
  - (413, 'Line exceeds 80 characters')
  - (414, 'Line exceeds 80 characters')
  - (416, 'Hardcoded string found')
  - (417, 'Hardcoded string found')
  - (422, 'Line exceeds 80 characters')
  - (423, 'Line exceeds 80 characters')
  - (425, 'Hardcoded string found')
  - (430, 'Line exceeds 80 characters')
  - (431, 'Line exceeds 80 characters')
  - (433, 'Hardcoded string found')
  - (438, 'Line exceeds 80 characters')
  - (439, 'Line exceeds 80 characters')
  - (445, 'Line exceeds 80 characters')
  - (446, 'Line exceeds 80 characters')
  - (448, 'Hardcoded string found')
  - (449, 'Hardcoded string found')
  - (450, 'Hardcoded string found')
  - (455, 'Line exceeds 80 characters')
  - (456, 'Line exceeds 80 characters')
  - (458, 'Hardcoded string found')
  - (459, 'Hardcoded string found')
  - (460, 'Hardcoded string found')
  - (461, 'Hardcoded string found')
  - (466, 'Line exceeds 80 characters')
  - (467, 'Line exceeds 80 characters')
  - (469, 'Hardcoded string found')
  - (470, 'Hardcoded string found')
  - (475, 'Line exceeds 80 characters')
  - (476, 'Line exceeds 80 characters')
  - (478, 'Hardcoded string found')
  - (479, 'Hardcoded string found')
  - (480, 'Hardcoded string found')
  - (485, 'Line exceeds 80 characters')
  - (486, 'Line exceeds 80 characters')
  - (488, 'Hardcoded string found')
  - (489, 'Hardcoded string found')
  - (490, 'Hardcoded string found')
  - (491, 'Hardcoded string found')
  - (492, 'Hardcoded string found')
  - (497, 'Line exceeds 80 characters')
  - (498, 'Line exceeds 80 characters')
  - (500, 'Hardcoded string found')
  - (501, 'Hardcoded string found')
  - (506, 'Line exceeds 80 characters')
  - (507, 'Line exceeds 80 characters')
  - (509, 'Hardcoded string found')
  - (510, 'Hardcoded string found')
  - (515, 'Line exceeds 80 characters')
  - (516, 'Line exceeds 80 characters')
  - (518, 'Hardcoded string found')
  - (523, 'Line exceeds 80 characters')
  - (524, 'Line exceeds 80 characters')
  - (526, 'Hardcoded string found')
  - (531, 'Line exceeds 80 characters')
  - (532, 'Line exceeds 80 characters')
  - (534, 'Hardcoded string found')
  - (535, 'Hardcoded string found')
  - (540, 'Line exceeds 80 characters')
  - (541, 'Line exceeds 80 characters')
  - (543, 'Hardcoded string found')
  - (544, 'Hardcoded string found')
  - (545, 'Hardcoded string found')
  - (546, 'Hardcoded string found')
  - (552, 'Line exceeds 80 characters')
  - (553, 'Line exceeds 80 characters')
  - (555, 'Hardcoded string found')
  - (556, 'Hardcoded string found')
  - (557, 'Hardcoded string found')
  - (558, 'Hardcoded string found')
  - (563, 'Line exceeds 80 characters')
  - (564, 'Line exceeds 80 characters')
  - (566, 'Hardcoded string found')
  - (567, 'Hardcoded string found')
  - (568, 'Hardcoded string found')
  - (569, 'Hardcoded string found')
  - (570, 'Hardcoded string found')
  - (575, 'Line exceeds 80 characters')
  - (576, 'Line exceeds 80 characters')
  - (578, 'Hardcoded string found')
  - (583, 'Line exceeds 80 characters')
  - (584, 'Line exceeds 80 characters')
  - (586, 'Hardcoded string found')
  - (587, 'Hardcoded string found')
  - (588, 'Hardcoded string found')
  - (589, 'Hardcoded string found')
  - (594, 'Line exceeds 80 characters')
  - (595, 'Line exceeds 80 characters')
  - (597, 'Hardcoded string found')
  - (602, 'Line exceeds 80 characters')
  - (603, 'Line exceeds 80 characters')
  - (609, 'Line exceeds 80 characters')
  - (610, 'Line exceeds 80 characters')
  - (612, 'Hardcoded string found')
  - (613, 'Hardcoded string found')
  - (618, 'Line exceeds 80 characters')
  - (619, 'Line exceeds 80 characters')
  - (621, 'Hardcoded string found')
  - (622, 'Hardcoded string found')
  - (623, 'Hardcoded string found')
  - (628, 'Line exceeds 80 characters')
  - (629, 'Line exceeds 80 characters')
  - (631, 'Hardcoded string found')
  - (632, 'Hardcoded string found')
  - (633, 'Hardcoded string found')
  - (634, 'Hardcoded string found')
  - (639, 'Line exceeds 80 characters')
  - (640, 'Line exceeds 80 characters')
  - (642, 'Hardcoded string found')
  - (647, 'Line exceeds 80 characters')
  - (648, 'Line exceeds 80 characters')
  - (650, 'Hardcoded string found')
  - (655, 'Line exceeds 80 characters')
  - (656, 'Line exceeds 80 characters')
  - (658, 'Hardcoded string found')
  - (659, 'Hardcoded string found')
  - (664, 'Line exceeds 80 characters')
  - (665, 'Line exceeds 80 characters')
  - (667, 'Hardcoded string found')
  - (672, 'Line exceeds 80 characters')
  - (673, 'Line exceeds 80 characters')
  - (677, 'Line exceeds 80 characters')
  - (678, 'Line exceeds 80 characters')
  - (684, 'Line exceeds 80 characters')
  - (685, 'Line exceeds 80 characters')
  - (687, 'Hardcoded string found')
  - (688, 'Hardcoded string found')
  - (689, 'Hardcoded string found')
  - (690, 'Hardcoded string found')
  - (695, 'Line exceeds 80 characters')
  - (696, 'Line exceeds 80 characters')
  - (698, 'Hardcoded string found')
  - (699, 'Hardcoded string found')
  - (700, 'Hardcoded string found')
  - (701, 'Hardcoded string found')
  - (702, 'Hardcoded string found')
  - (707, 'Line exceeds 80 characters')
  - (708, 'Line exceeds 80 characters')
  - (710, 'Hardcoded string found')
  - (711, 'Hardcoded string found')
  - (716, 'Line exceeds 80 characters')
  - (717, 'Line exceeds 80 characters')
  - (721, 'Line exceeds 80 characters')
  - (722, 'Line exceeds 80 characters')
  - (724, 'Hardcoded string found')
  - (725, 'Hardcoded string found')
  - (730, 'Line exceeds 80 characters')
  - (731, 'Line exceeds 80 characters')
  - (737, 'Line exceeds 80 characters')
  - (738, 'Line exceeds 80 characters')
  - (744, 'Line exceeds 80 characters')
  - (745, 'Line exceeds 80 characters')
  - (747, 'Hardcoded string found')
  - (752, 'Line exceeds 80 characters')
  - (753, 'Line exceeds 80 characters')
  - (759, 'Line exceeds 80 characters')
  - (760, 'Line exceeds 80 characters')
  - (766, 'Line exceeds 80 characters')
  - (767, 'Line exceeds 80 characters')
  - (769, 'Hardcoded string found')
  - (774, 'Line exceeds 80 characters')
  - (775, 'Line exceeds 80 characters')
  - (781, 'Line exceeds 80 characters')
  - (782, 'Line exceeds 80 characters')
  - (784, 'Hardcoded string found')
  - (785, 'Hardcoded string found')
  - (791, 'Line exceeds 80 characters')
  - (792, 'Line exceeds 80 characters')
  - (794, 'Hardcoded string found')
  - (795, 'Hardcoded string found')
  - (796, 'Hardcoded string found')
  - (797, 'Hardcoded string found')
  - (798, 'Hardcoded string found')
  - (803, 'Line exceeds 80 characters')
  - (804, 'Line exceeds 80 characters')
  - (810, 'Line exceeds 80 characters')
  - (811, 'Line exceeds 80 characters')
  - (817, 'Line exceeds 80 characters')
  - (818, 'Line exceeds 80 characters')
  - (824, 'Line exceeds 80 characters')
  - (825, 'Line exceeds 80 characters')
  - (827, 'Hardcoded string found')
  - (832, 'Line exceeds 80 characters')
  - (833, 'Line exceeds 80 characters')
  - (835, 'Hardcoded string found')
  - (840, 'Line exceeds 80 characters')
  - (841, 'Line exceeds 80 characters')
  - (847, 'Line exceeds 80 characters')
  - (848, 'Line exceeds 80 characters')
  - (850, 'Hardcoded string found')
  - (856, 'Line exceeds 80 characters')
  - (857, 'Line exceeds 80 characters')
  - (859, 'Hardcoded string found')
  - (860, 'Hardcoded string found')
  - (865, 'Line exceeds 80 characters')
  - (866, 'Line exceeds 80 characters')
  - (872, 'Line exceeds 80 characters')
  - (873, 'Line exceeds 80 characters')
  - (875, 'Hardcoded string found')
  - (880, 'Line exceeds 80 characters')
  - (881, 'Line exceeds 80 characters')
  - (883, 'Hardcoded string found')
  - (884, 'Hardcoded string found')
  - (889, 'Line exceeds 80 characters')
  - (890, 'Line exceeds 80 characters')
  - (896, 'Line exceeds 80 characters')
  - (903, 'Line exceeds 80 characters')
  - (904, 'Line exceeds 80 characters')
  - (917, 'Line exceeds 80 characters')
  - (918, 'Line exceeds 80 characters')
  - (920, 'Hardcoded string found')
  - (921, 'Hardcoded string found')
  - (922, 'Hardcoded string found')
  - (943, 'Line exceeds 80 characters')
  - (945, 'Line exceeds 80 characters')
  - (946, 'Line exceeds 80 characters')
  - (950, 'Line exceeds 80 characters')
  - (951, 'Line exceeds 80 characters')
  - (954, 'Line exceeds 80 characters')
  - (955, 'Line exceeds 80 characters')
  - (957, 'Hardcoded string found')
  - (958, 'Hardcoded string found')
  - (959, 'Hardcoded string found')
  - (960, 'Hardcoded string found')
  - (964, 'Line exceeds 80 characters')
  - (965, 'Line exceeds 80 characters')
  - (968, 'Line exceeds 80 characters')
  - (969, 'Line exceeds 80 characters')
  - (971, 'Hardcoded string found')
  - (979, 'Line exceeds 80 characters')
  - (980, 'Line exceeds 80 characters')
  - (983, 'Line exceeds 80 characters')
  - (984, 'Line exceeds 80 characters')
  - (986, 'Hardcoded string found')
  - (987, 'Hardcoded string found')
  - (988, 'Hardcoded string found')
  - (989, 'Hardcoded string found')
  - (990, 'Hardcoded string found')
  - (991, 'Hardcoded string found')
  - (998, 'Line exceeds 80 characters')
  - (999, 'Line exceeds 80 characters')
  - (1002, 'Line exceeds 80 characters')
  - (1003, 'Line exceeds 80 characters')
  - (1005, 'Hardcoded string found')
  - (1006, 'Hardcoded string found')
  - (1007, 'Hardcoded string found')
  - (1014, 'Line exceeds 80 characters')
  - (1015, 'Line exceeds 80 characters')
  - (1018, 'Line exceeds 80 characters')
  - (1019, 'Line exceeds 80 characters')
  - (1023, 'Line exceeds 80 characters')
  - (1024, 'Line exceeds 80 characters')
  - (1026, 'Hardcoded string found')
  - (1027, 'Hardcoded string found')
  - (1028, 'Hardcoded string found')
  - (1029, 'Hardcoded string found')
  - (1030, 'Hardcoded string found')
  - (1031, 'Hardcoded string found')
  - (1032, 'Hardcoded string found')
  - (1033, 'Hardcoded string found')
  - (1048, 'Line exceeds 80 characters')
  - (1049, 'Line exceeds 80 characters')
  - (1051, 'Hardcoded string found')
  - (1052, 'Hardcoded string found')
  - (1053, 'Hardcoded string found')
  - (1054, 'Hardcoded string found')
  - (1055, 'Hardcoded string found')
  - (1056, 'Hardcoded string found')
  - (1057, 'Hardcoded string found')
  - (1058, 'Hardcoded string found')
  - (1062, 'Line exceeds 80 characters')
  - (1063, 'Line exceeds 80 characters')
  - (1066, 'Line exceeds 80 characters')
  - (1067, 'Line exceeds 80 characters')
  - (1069, 'Hardcoded string found')
  - (1070, 'Hardcoded string found')
  - (1071, 'Hardcoded string found')
  - (1072, 'Hardcoded string found')
  - (1077, 'Line exceeds 80 characters')
  - (1078, 'Line exceeds 80 characters')
  - (1080, 'Hardcoded string found')
  - (1081, 'Hardcoded string found')
  - (1082, 'Hardcoded string found')
  - (1083, 'Hardcoded string found')
  - (1084, 'Hardcoded string found')
  - (1085, 'Hardcoded string found')
  - (1086, 'Hardcoded string found')
  - (1087, 'Hardcoded string found')
  - (1091, 'Line exceeds 80 characters')
  - (1092, 'Line exceeds 80 characters')
  - (1094, 'Hardcoded string found')
  - (1095, 'Hardcoded string found')
  - (1096, 'Hardcoded string found')
  - (1097, 'Hardcoded string found')
  - (1098, 'Hardcoded string found')
  - (1115, 'Line exceeds 80 characters')
  - (1116, 'Line exceeds 80 characters')
  - (1118, 'Hardcoded string found')
  - (1119, 'Hardcoded string found')
  - (1127, 'Line exceeds 80 characters')
  - (1132, 'Line exceeds 80 characters')
  - (1133, 'Line exceeds 80 characters')
  - (1135, 'Line exceeds 80 characters')
  - (1136, 'Line exceeds 80 characters')
  - (1143, 'Line exceeds 80 characters')
  - (1144, 'Line exceeds 80 characters')
  - (1146, 'Hardcoded string found')
  - (1147, 'Hardcoded string found')
  - (1148, 'Hardcoded string found')
  - (1165, 'Line exceeds 80 characters')
  - (1168, 'Line exceeds 80 characters')
  - (1172, 'Line exceeds 80 characters')
  - (1173, 'Line exceeds 80 characters')
  - (1177, 'Line exceeds 80 characters')
  - (1184, 'Line exceeds 80 characters')
  - (1185, 'Line exceeds 80 characters')
  - (1198, 'Line exceeds 80 characters')
  - (1199, 'Line exceeds 80 characters')
  - (1210, 'Line exceeds 80 characters')
  - (1211, 'Line exceeds 80 characters')
  - (1213, 'Hardcoded string found')
  - (1214, 'Hardcoded string found')
  - (1234, 'Line exceeds 80 characters')
  - (1241, 'Line exceeds 80 characters')
  - (1242, 'Line exceeds 80 characters')
  - (1248, 'Line exceeds 80 characters')
  - (1255, 'Line exceeds 80 characters')
  - (1256, 'Line exceeds 80 characters')
  - (1267, 'Line exceeds 80 characters')
  - (1274, 'Line exceeds 80 characters')
  - (1275, 'Line exceeds 80 characters')
  - (1282, 'Line exceeds 80 characters')
  - (1290, 'Line exceeds 80 characters')
  - (1291, 'Line exceeds 80 characters')
  - (1295, 'Line exceeds 80 characters')
  - (1296, 'Line exceeds 80 characters')
  - (1303, 'Line exceeds 80 characters')
  - (1304, 'Line exceeds 80 characters')
  - (1311, 'Line exceeds 80 characters')
  - (1312, 'Line exceeds 80 characters')
  - (1314, 'Hardcoded string found')
  - (1321, 'Line exceeds 80 characters')
  - (1323, 'Line exceeds 80 characters')
  - (1324, 'Line exceeds 80 characters')
  - (1326, 'Line exceeds 80 characters')
  - (1329, 'Line exceeds 80 characters')
  - (1330, 'Line exceeds 80 characters')
  - (1337, 'Line exceeds 80 characters')
  - (1338, 'Line exceeds 80 characters')
  - (1346, 'Line exceeds 80 characters')
  - (1353, 'Line exceeds 80 characters')
  - (1354, 'Line exceeds 80 characters')
  - (1360, 'Line exceeds 80 characters')
  - (1368, 'Line exceeds 80 characters')
  - (1369, 'Line exceeds 80 characters')
  - (1376, 'Line exceeds 80 characters')
  - (1377, 'Line exceeds 80 characters')
  - (1384, 'Line exceeds 80 characters')
  - (1391, 'Line exceeds 80 characters')
  - (1392, 'Line exceeds 80 characters')
  - (1399, 'Line exceeds 80 characters')
  - (1400, 'Line exceeds 80 characters')
  - (1407, 'Line exceeds 80 characters')
  - (1408, 'Line exceeds 80 characters')
  - (1415, 'Line exceeds 80 characters')
  - (1416, 'Line exceeds 80 characters')
  - (1429, 'Line exceeds 80 characters')
  - (1430, 'Line exceeds 80 characters')
  - (1441, 'Line exceeds 80 characters')
  - (1442, 'Line exceeds 80 characters')
  - (1455, 'Line exceeds 80 characters')
  - (1456, 'Line exceeds 80 characters')
  - (1460, 'Line exceeds 80 characters')
  - (1467, 'Line exceeds 80 characters')
  - (1468, 'Line exceeds 80 characters')
  - (1479, 'Line exceeds 80 characters')
  - (1480, 'Line exceeds 80 characters')
  - (1484, 'Line exceeds 80 characters')
  - (1485, 'Line exceeds 80 characters')
  - (1486, 'Line exceeds 80 characters')
  - (1487, 'Line exceeds 80 characters')
  - (1491, 'Line exceeds 80 characters')
  - (1492, 'Line exceeds 80 characters')
  - (1496, 'Line exceeds 80 characters')
  - (1497, 'Line exceeds 80 characters')
  - (1502, 'Line exceeds 80 characters')
  - (1503, 'Line exceeds 80 characters')
  - (1504, 'Line exceeds 80 characters')
  - (1508, 'Line exceeds 80 characters')
  - (1509, 'Line exceeds 80 characters')
  - (1513, 'Line exceeds 80 characters')
  - (1515, 'Line exceeds 80 characters')
  - (1520, 'Line exceeds 80 characters')
  - (1521, 'Line exceeds 80 characters')
  - (1525, 'Line exceeds 80 characters')
  - (1527, 'Line exceeds 80 characters')
  - (1528, 'Line exceeds 80 characters')
  - (1532, 'Line exceeds 80 characters')
  - (1533, 'Line exceeds 80 characters')
  - (1537, 'Line exceeds 80 characters')
  - (1544, 'Line exceeds 80 characters')
  - (1545, 'Line exceeds 80 characters')
  - (1553, 'Line exceeds 80 characters')
  - (1554, 'Line exceeds 80 characters')
  - (1563, 'Line exceeds 80 characters')
  - (1565, 'Line exceeds 80 characters')
  - (1566, 'Line exceeds 80 characters')
  - (1571, 'Line exceeds 80 characters')
  - (1576, 'Line exceeds 80 characters')
  - (1577, 'Line exceeds 80 characters')
  - (1584, 'Line exceeds 80 characters')
  - (1588, 'Line exceeds 80 characters')
  - (1596, 'Line exceeds 80 characters')
  - (1597, 'Line exceeds 80 characters')
  - (1604, 'Line exceeds 80 characters')
  - (1605, 'Line exceeds 80 characters')
  - (1609, 'Line exceeds 80 characters')
  - (1618, 'Line exceeds 80 characters')
  - (1624, 'Line exceeds 80 characters')
  - (1626, 'Line exceeds 80 characters')
  - (1627, 'Line exceeds 80 characters')

**Comment by billmbowling3** [comment]
I got it.
