### ISSUE TITLE
Issue-feat: update get metadata

### ISSUE THREAD

**Issue by kazupot7** [kazupot7/token-creator#209]
Automated Review Comments
Issues in src/components/GetMetadata.tsx:
  - (1, 'Hardcoded string found')
  - (42, 'Line exceeds 80 characters')
  - (46, 'Line exceeds 80 characters')
  - (47, 'Line exceeds 80 characters')
  - (47, 'Hardcoded string found')
  - (50, 'Line exceeds 80 characters')
  - (54, 'Line exceeds 80 characters')
  - (58, 'Line exceeds 80 characters')
  - (62, 'Line exceeds 80 characters')
  - (63, 'Hardcoded string found')
  - (66, 'Line exceeds 80 characters')
  - (70, 'Line exceeds 80 characters')
  - (71, 'Line exceeds 80 characters')
  - (86, 'Line exceeds 80 characters')
  - (90, 'Line exceeds 80 characters')
  - (91, 'Line exceeds 80 characters')
  - (91, 'Hardcoded string found')
  - (94, 'Line exceeds 80 characters')
  - (98, 'Line exceeds 80 characters')
  - (102, 'Line exceeds 80 characters')
  - (106, 'Line exceeds 80 characters')
  - (107, 'Hardcoded string found')
  - (110, 'Line exceeds 80 characters')
  - (114, 'Line exceeds 80 characters')
  - (115, 'Line exceeds 80 characters')

**Comment by glory1001** [comment]
I got it.
