### ISSUE TITLE
Issue-add update metadata page

### ISSUE THREAD

**Issue by kazupot7** [kazupot7/token-creator#211]
Automated Review Comments
Issues in src/components/AppBar.tsx:
  - (5, 'Line exceeds 80 characters')
  - (8, 'Line exceeds 80 characters')
  - (15, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (26, 'Line exceeds 80 characters')
  - (28, 'Line exceeds 80 characters')
  - (32, 'Line exceeds 80 characters')
  - (33, 'Hardcoded string found')
  - (34, 'Line exceeds 80 characters')
  - (35, 'Hardcoded string found')
  - (38, 'Line exceeds 80 characters')
  - (39, 'Hardcoded string found')
  - (40, 'Line exceeds 80 characters')
  - (41, 'Hardcoded string found')
  - (44, 'Line exceeds 80 characters')
  - (45, 'Hardcoded string found')
  - (46, 'Line exceeds 80 characters')
  - (47, 'Hardcoded string found')
  - (50, 'Line exceeds 80 characters')
  - (51, 'Hardcoded string found')
  - (52, 'Line exceeds 80 characters')
  - (53, 'Hardcoded string found')
  - (56, 'Line exceeds 80 characters')
  - (57, 'Hardcoded string found')
  - (58, 'Line exceeds 80 characters')
  - (59, 'Hardcoded string found')
  - (62, 'Line exceeds 80 characters')
  - (63, 'Hardcoded string found')
  - (64, 'Line exceeds 80 characters')
  - (65, 'Hardcoded string found')
  - (75, 'Hardcoded string found')
  - (87, 'Hardcoded string found')
  - (97, 'Hardcoded string found')
  - (99, 'Hardcoded string found')
  - (124, 'Hardcoded string found')
  - (129, 'Hardcoded string found')
  - (134, 'Hardcoded string found')
  - (136, 'Hardcoded string found')
  - (139, 'Hardcoded string found')
  - (141, 'Hardcoded string found')
  - (144, 'Hardcoded string found')
  - (145, 'Hardcoded string found')
  - (146, 'Hardcoded string found')
  - (147, 'Hardcoded string found')
  - (149, 'Line exceeds 80 characters')
  - (150, 'Line exceeds 80 characters')
  - (153, 'Hardcoded string found')
  - (154, 'Hardcoded string found')
  - (155, 'Hardcoded string found')
  - (156, 'Hardcoded string found')
  - (165, 'Line exceeds 80 characters')
  - (166, 'Line exceeds 80 characters')
  - (175, 'Hardcoded string found')
  - (176, 'Hardcoded string found')
  - (179, 'Hardcoded string found')
  - (180, 'Hardcoded string found')
Issues in src/components/UpdateMetadata.tsx:
  - (2, 'Hardcoded string found')
  - (4, 'Line exceeds 80 characters')
  - (5, 'Line exceeds 80 characters')
  - (12, 'Line exceeds 80 characters')
  - (61, 'Hardcoded string found')
  - (62, 'Line exceeds 80 characters')
  - (63, 'Hardcoded string found')
  - (67, 'Hardcoded string found')
  - (68, 'Line exceeds 80 characters')
  - (69, 'Hardcoded string found')
  - (73, 'Hardcoded string found')
  - (74, 'Line exceeds 80 characters')
  - (75, 'Hardcoded string found')
  - (79, 'Hardcoded string found')
  - (80, 'Line exceeds 80 characters')
  - (81, 'Hardcoded string found')
  - (85, 'Line exceeds 80 characters')
Issues in src/pages/update.tsx:
  - (2, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
Issues in src/views/update/index.tsx:
  - (2, 'Hardcoded string found')
  - (12, 'Line exceeds 80 characters')

**Comment by brandonabeal110** [comment]
I got it.
