### ISSUE TITLE
Issue-fix: upgrade to metadata v3

### ISSUE THREAD

**Issue by kazupot7** [kazupot7/token-creator#218]
Automated Review Comments
Issues in .eslintrc.json:
  - (3, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
Issues in package.json:
  - (12, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
  - (26, 'Hardcoded string found')
Issues in src/components/CreateToken.tsx:
  - (2, 'Hardcoded string found')
  - (5, 'Line exceeds 80 characters')
  - (6, 'Line exceeds 80 characters')
  - (7, 'Line exceeds 80 characters')
  - (9, 'Line exceeds 80 characters')
  - (18, 'Line exceeds 80 characters')
  - (29, 'Line exceeds 80 characters')
  - (33, 'Hardcoded string found')
  - (83, 'Line exceeds 80 characters')
Issues in src/components/GetMetadata.tsx:
  - (4, 'Line exceeds 80 characters')
  - (5, 'Line exceeds 80 characters')
  - (6, 'Line exceeds 80 characters')
  - (6, 'Hardcoded string found')

**Comment by Muray1008** [comment]
I got it.
