### ISSUE TITLE
Issue-fix: updated getMetadata

### ISSUE THREAD

**Issue by kazupot7** [kazupot7/token-creator#220]
Automated Review Comments
Issues in src/components/GetMetadata.tsx:
  - (2, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
Issues in src/components/UpdateMetadata.tsx:
  - (18, 'Hardcoded string found')
Issues in yarn.lock:
  - (3, 'Line exceeds 80 characters')
  - (8, 'Line exceeds 80 characters')
  - (10, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (17, 'Line exceeds 80 characters')
  - (19, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (25, 'Line exceeds 80 characters')
  - (26, 'Line exceeds 80 characters')
  - (32, 'Line exceeds 80 characters')
  - (33, 'Line exceeds 80 characters')
  - (35, 'Hardcoded string found')
  - (36, 'Hardcoded string found')
  - (37, 'Hardcoded string found')
  - (38, 'Hardcoded string found')
  - (39, 'Hardcoded string found')
  - (40, 'Hardcoded string found')
  - (45, 'Line exceeds 80 characters')
  - (46, 'Line exceeds 80 characters')
  - (48, 'Hardcoded string found')
  - (49, 'Hardcoded string found')
  - (50, 'Hardcoded string found')
  - (51, 'Hardcoded string found')
  - (52, 'Hardcoded string found')
  - (53, 'Hardcoded string found')
  - (54, 'Hardcoded string found')
  - (59, 'Line exceeds 80 characters')
  - (60, 'Line exceeds 80 characters')
  - (62, 'Hardcoded string found')
  - (63, 'Hardcoded string found')
  - (68, 'Line exceeds 80 characters')
  - (69, 'Line exceeds 80 characters')
  - (76, 'Line exceeds 80 characters')
  - (78, 'Hardcoded string found')
  - (79, 'Hardcoded string found')
  - (84, 'Line exceeds 80 characters')
  - (85, 'Line exceeds 80 characters')
  - (87, 'Hardcoded string found')
  - (88, 'Hardcoded string found')
  - (89, 'Hardcoded string found')
  - (90, 'Hardcoded string found')
  - (91, 'Hardcoded string found')
  - (92, 'Hardcoded string found')
  - (93, 'Hardcoded string found')
  - (94, 'Hardcoded string found')
  - (95, 'Hardcoded string found')
  - (96, 'Hardcoded string found')
  - (97, 'Hardcoded string found')
  - (98, 'Hardcoded string found')
  - (99, 'Hardcoded string found')
  - (100, 'Hardcoded string found')
  - (101, 'Hardcoded string found')
  - (102, 'Hardcoded string found')
  - (103, 'Hardcoded string found')
  - (104, 'Hardcoded string found')
  - (105, 'Hardcoded string found')
  - (106, 'Hardcoded string found')
  - (107, 'Hardcoded string found')
  - (108, 'Hardcoded string found')
  - (109, 'Hardcoded string found')
  - (110, 'Hardcoded string found')
  - (111, 'Hardcoded string found')
  - (112, 'Hardcoded string found')
  - (113, 'Hardcoded string found')
  - (114, 'Hardcoded string found')
  - (115, 'Hardcoded string found')
  - (116, 'Hardcoded string found')
  - (117, 'Hardcoded string found')
  - (118, 'Hardcoded string found')
  - (119, 'Hardcoded string found')
  - (120, 'Hardcoded string found')
  - (121, 'Hardcoded string found')
  - (122, 'Hardcoded string found')
  - (123, 'Hardcoded string found')
  - (124, 'Hardcoded string found')
  - (125, 'Hardcoded string found')
  - (126, 'Hardcoded string found')
  - (127, 'Hardcoded string found')
  - (128, 'Hardcoded string found')
  - (129, 'Hardcoded string found')
  - (130, 'Hardcoded string found')
  - (131, 'Hardcoded string found')
  - (132, 'Hardcoded string found')
  - (133, 'Hardcoded string found')
  - (134, 'Hardcoded string found')
  - (135, 'Hardcoded string found')
  - (136, 'Hardcoded string found')
  - (137, 'Hardcoded string found')
  - (138, 'Hardcoded string found')
  - (139, 'Hardcoded string found')
  - (140, 'Hardcoded string found')
  - (141, 'Hardcoded string found')
  - (147, 'Line exceeds 80 characters')
  - (148, 'Line exceeds 80 characters')
  - (150, 'Hardcoded string found')
  - (151, 'Hardcoded string found')
  - (152, 'Hardcoded string found')
  - (153, 'Hardcoded string found')
  - (154, 'Hardcoded string found')
  - (155, 'Hardcoded string found')
  - (156, 'Hardcoded string found')
  - (157, 'Hardcoded string found')
  - (158, 'Hardcoded string found')
  - (159, 'Hardcoded string found')
  - (160, 'Hardcoded string found')
  - (161, 'Hardcoded string found')
  - (162, 'Hardcoded string found')
  - (163, 'Hardcoded string found')
  - (164, 'Hardcoded string found')
  - (165, 'Hardcoded string found')
  - (166, 'Hardcoded string found')
  - (167, 'Hardcoded string found')
  - (168, 'Hardcoded string found')
  - (169, 'Hardcoded string found')
  - (170, 'Hardcoded string found')
  - (171, 'Hardcoded string found')
  - (172, 'Hardcoded string found')
  - (173, 'Hardcoded string found')
  - (174, 'Hardcoded string found')
  - (175, 'Hardcoded string found')
  - (176, 'Hardcoded string found')
  - (177, 'Hardcoded string found')
  - (178, 'Hardcoded string found')
  - (179, 'Hardcoded string found')
  - (180, 'Hardcoded string found')
  - (181, 'Hardcoded string found')
  - (182, 'Hardcoded string found')
  - (183, 'Hardcoded string found')
  - (184, 'Hardcoded string found')
  - (189, 'Line exceeds 80 characters')
  - (190, 'Line exceeds 80 characters')
  - (192, 'Hardcoded string found')
  - (193, 'Hardcoded string found')
  - (194, 'Hardcoded string found')
  - (195, 'Hardcoded string found')
  - (196, 'Hardcoded string found')
  - (197, 'Hardcoded string found')
  - (198, 'Hardcoded string found')
  - (199, 'Hardcoded string found')
  - (200, 'Hardcoded string found')
  - (201, 'Hardcoded string found')
  - (202, 'Hardcoded string found')
  - (203, 'Hardcoded string found')
  - (204, 'Hardcoded string found')
  - (205, 'Hardcoded string found')
  - (206, 'Hardcoded string found')
  - (207, 'Hardcoded string found')
  - (208, 'Hardcoded string found')
  - (209, 'Hardcoded string found')
  - (210, 'Hardcoded string found')
  - (211, 'Hardcoded string found')
  - (212, 'Hardcoded string found')
  - (213, 'Hardcoded string found')
  - (214, 'Hardcoded string found')
  - (215, 'Hardcoded string found')
  - (216, 'Hardcoded string found')
  - (217, 'Hardcoded string found')
  - (218, 'Hardcoded string found')
  - (219, 'Hardcoded string found')
  - (220, 'Hardcoded string found')
  - (221, 'Hardcoded string found')
  - (222, 'Hardcoded string found')
  - (223, 'Hardcoded string found')
  - (224, 'Hardcoded string found')
  - (225, 'Hardcoded string found')
  - (226, 'Hardcoded string found')
  - (227, 'Hardcoded string found')
  - (228, 'Hardcoded string found')
  - (229, 'Hardcoded string found')
  - (236, 'Line exceeds 80 characters')
  - (238, 'Hardcoded string found')
  - (242, 'Line exceeds 80 characters')
  - (243, 'Line exceeds 80 characters')
  - (245, 'Hardcoded string found')
  - (246, 'Hardcoded string found')
  - (247, 'Hardcoded string found')
  - (252, 'Line exceeds 80 characters')
  - (253, 'Line exceeds 80 characters')
  - (255, 'Hardcoded string found')
  - (256, 'Hardcoded string found')
  - (257, 'Hardcoded string found')
  - (258, 'Hardcoded string found')
  - (259, 'Hardcoded string found')
  - (260, 'Hardcoded string found')
  - (261, 'Hardcoded string found')
  - (262, 'Hardcoded string found')
  - (263, 'Hardcoded string found')
  - (268, 'Line exceeds 80 characters')
  - (269, 'Line exceeds 80 characters')
  - (271, 'Hardcoded string found')
  - (272, 'Hardcoded string found')
  - (273, 'Hardcoded string found')
  - (274, 'Hardcoded string found')
  - (275, 'Hardcoded string found')
  - (276, 'Hardcoded string found')
  - (277, 'Hardcoded string found')
  - (278, 'Hardcoded string found')
  - (279, 'Hardcoded string found')
  - (280, 'Hardcoded string found')
  - (285, 'Line exceeds 80 characters')
  - (286, 'Line exceeds 80 characters')
  - (288, 'Hardcoded string found')
  - (289, 'Hardcoded string found')
  - (290, 'Hardcoded string found')
  - (291, 'Hardcoded string found')
  - (296, 'Line exceeds 80 characters')
  - (297, 'Line exceeds 80 characters')
  - (299, 'Hardcoded string found')
  - (300, 'Hardcoded string found')
  - (301, 'Hardcoded string found')
  - (302, 'Hardcoded string found')
  - (303, 'Hardcoded string found')
  - (304, 'Hardcoded string found')
  - (309, 'Line exceeds 80 characters')
  - (310, 'Line exceeds 80 characters')
  - (312, 'Hardcoded string found')
  - (313, 'Hardcoded string found')
  - (314, 'Hardcoded string found')
  - (319, 'Line exceeds 80 characters')
  - (320, 'Line exceeds 80 characters')
  - (322, 'Hardcoded string found')
  - (323, 'Hardcoded string found')
  - (324, 'Hardcoded string found')
  - (325, 'Hardcoded string found')
  - (326, 'Hardcoded string found')
  - (327, 'Hardcoded string found')
  - (332, 'Line exceeds 80 characters')
  - (333, 'Line exceeds 80 characters')
  - (335, 'Hardcoded string found')
  - (336, 'Hardcoded string found')
  - (337, 'Hardcoded string found')
  - (342, 'Line exceeds 80 characters')
  - (343, 'Line exceeds 80 characters')
  - (345, 'Hardcoded string found')
  - (346, 'Hardcoded string found')
  - (347, 'Hardcoded string found')
  - (348, 'Hardcoded string found')
  - (349, 'Hardcoded string found')
  - (350, 'Hardcoded string found')
  - (351, 'Hardcoded string found')
  - (356, 'Line exceeds 80 characters')
  - (357, 'Line exceeds 80 characters')
  - (359, 'Hardcoded string found')
  - (360, 'Hardcoded string found')
  - (361, 'Hardcoded string found')
  - (366, 'Line exceeds 80 characters')
  - (367, 'Line exceeds 80 characters')
  - (369, 'Hardcoded string found')
  - (370, 'Hardcoded string found')
  - (375, 'Line exceeds 80 characters')
  - (376, 'Line exceeds 80 characters')
  - (378, 'Hardcoded string found')
  - (379, 'Hardcoded string found')
  - (384, 'Line exceeds 80 characters')
  - (385, 'Line exceeds 80 characters')
  - (387, 'Hardcoded string found')
  - (388, 'Hardcoded string found')
  - (389, 'Hardcoded string found')
  - (394, 'Line exceeds 80 characters')
  - (395, 'Line exceeds 80 characters')
  - (397, 'Hardcoded string found')
  - (398, 'Hardcoded string found')
  - (399, 'Hardcoded string found')
  - (400, 'Hardcoded string found')
  - (401, 'Hardcoded string found')
  - (406, 'Line exceeds 80 characters')
  - (407, 'Line exceeds 80 characters')
  - (409, 'Hardcoded string found')
  - (410, 'Hardcoded string found')
  - (411, 'Hardcoded string found')
  - (416, 'Line exceeds 80 characters')
  - (417, 'Line exceeds 80 characters')
  - (419, 'Hardcoded string found')
  - (420, 'Hardcoded string found')
  - (421, 'Hardcoded string found')
  - (422, 'Hardcoded string found')
  - (423, 'Hardcoded string found')
  - (424, 'Hardcoded string found')
  - (429, 'Line exceeds 80 characters')
  - (430, 'Line exceeds 80 characters')
  - (432, 'Hardcoded string found')
  - (433, 'Hardcoded string found')
  - (438, 'Line exceeds 80 characters')
  - (439, 'Line exceeds 80 characters')
  - (441, 'Hardcoded string found')
  - (442, 'Hardcoded string found')
  - (443, 'Hardcoded string found')
  - (444, 'Hardcoded string found')
  - (449, 'Line exceeds 80 characters')
  - (450, 'Line exceeds 80 characters')
  - (452, 'Hardcoded string found')
  - (453, 'Hardcoded string found')
  - (454, 'Hardcoded string found')
  - (455, 'Hardcoded string found')
  - (460, 'Line exceeds 80 characters')
  - (461, 'Line exceeds 80 characters')
  - (463, 'Hardcoded string found')
  - (464, 'Hardcoded string found')
  - (465, 'Hardcoded string found')
  - (466, 'Hardcoded string found')
  - (471, 'Line exceeds 80 characters')
  - (472, 'Line exceeds 80 characters')
  - (474, 'Hardcoded string found')
  - (475, 'Hardcoded string found')
  - (476, 'Hardcoded string found')
  - (477, 'Hardcoded string found')
  - (478, 'Hardcoded string found')
  - (479, 'Hardcoded string found')
  - (480, 'Hardcoded string found')
  - (481, 'Hardcoded string found')
  - (482, 'Hardcoded string found')
  - (483, 'Hardcoded string found')
  - (484, 'Hardcoded string found')
  - (485, 'Hardcoded string found')
  - (486, 'Hardcoded string found')
  - (487, 'Hardcoded string found')
  - (488, 'Hardcoded string found')
  - (489, 'Hardcoded string found')
  - (490, 'Hardcoded string found')
  - (491, 'Hardcoded string found')
  - (492, 'Hardcoded string found')
  - (493, 'Hardcoded string found')
  - (494, 'Hardcoded string found')
  - (495, 'Hardcoded string found')
  - (496, 'Hardcoded string found')
  - (497, 'Hardcoded string found')
  - (498, 'Hardcoded string found')
  - (499, 'Hardcoded string found')
  - (500, 'Hardcoded string found')
  - (501, 'Hardcoded string found')
  - (502, 'Hardcoded string found')
  - (503, 'Hardcoded string found')
  - (504, 'Hardcoded string found')
  - (505, 'Hardcoded string found')
  - (506, 'Hardcoded string found')
  - (507, 'Hardcoded string found')
  - (508, 'Hardcoded string found')
  - (509, 'Hardcoded string found')
  - (515, 'Line exceeds 80 characters')
  - (517, 'Hardcoded string found')
  - (522, 'Line exceeds 80 characters')
  - (523, 'Line exceeds 80 characters')
  - (529, 'Line exceeds 80 characters')
  - (530, 'Line exceeds 80 characters')
  - (532, 'Hardcoded string found')
  - (533, 'Hardcoded string found')
  - (538, 'Line exceeds 80 characters')
  - (539, 'Line exceeds 80 characters')
  - (545, 'Line exceeds 80 characters')
  - (546, 'Line exceeds 80 characters')
  - (548, 'Hardcoded string found')
  - (549, 'Hardcoded string found')
  - (555, 'Line exceeds 80 characters')
  - (556, 'Line exceeds 80 characters')
  - (558, 'Hardcoded string found')
  - (559, 'Hardcoded string found')
  - (560, 'Hardcoded string found')
  - (565, 'Line exceeds 80 characters')
  - (566, 'Line exceeds 80 characters')
  - (572, 'Line exceeds 80 characters')
  - (573, 'Line exceeds 80 characters')
  - (579, 'Line exceeds 80 characters')
  - (587, 'Line exceeds 80 characters')
  - (588, 'Line exceeds 80 characters')
  - (595, 'Line exceeds 80 characters')
  - (596, 'Line exceeds 80 characters')
  - (598, 'Hardcoded string found')
  - (599, 'Hardcoded string found')
  - (601, 'Line exceeds 80 characters')
  - (603, 'Line exceeds 80 characters')
  - (604, 'Line exceeds 80 characters')
  - (606, 'Hardcoded string found')
  - (607, 'Hardcoded string found')
  - (613, 'Line exceeds 80 characters')
  - (620, 'Line exceeds 80 characters')
  - (621, 'Line exceeds 80 characters')
  - (629, 'Line exceeds 80 characters')
  - (630, 'Line exceeds 80 characters')
  - (638, 'Line exceeds 80 characters')
  - (639, 'Line exceeds 80 characters')
  - (647, 'Line exceeds 80 characters')
  - (648, 'Line exceeds 80 characters')
  - (653, 'Line exceeds 80 characters')
  - (655, 'Hardcoded string found')
  - (656, 'Hardcoded string found')
  - (657, 'Hardcoded string found')
  - (658, 'Hardcoded string found')
  - (659, 'Hardcoded string found')
  - (660, 'Hardcoded string found')
  - (661, 'Hardcoded string found')
  - (662, 'Hardcoded string found')
  - (663, 'Hardcoded string found')
  - (678, 'Line exceeds 80 characters')
  - (679, 'Line exceeds 80 characters')
  - (681, 'Hardcoded string found')
  - (682, 'Hardcoded string found')
  - (683, 'Hardcoded string found')
  - (684, 'Hardcoded string found')
  - (685, 'Hardcoded string found')
  - (690, 'Line exceeds 80 characters')
  - (691, 'Line exceeds 80 characters')
  - (693, 'Hardcoded string found')
  - (694, 'Hardcoded string found')
  - (695, 'Hardcoded string found')
  - (696, 'Hardcoded string found')
  - (697, 'Hardcoded string found')
  - (701, 'Line exceeds 80 characters')
  - (702, 'Line exceeds 80 characters')
  - (704, 'Hardcoded string found')
  - (707, 'Line exceeds 80 characters')
  - (710, 'Line exceeds 80 characters')
  - (711, 'Line exceeds 80 characters')
  - (714, 'Line exceeds 80 characters')
  - (718, 'Line exceeds 80 characters')
  - (719, 'Line exceeds 80 characters')
  - (721, 'Hardcoded string found')
  - (726, 'Line exceeds 80 characters')
  - (727, 'Line exceeds 80 characters')
  - (729, 'Hardcoded string found')
  - (734, 'Line exceeds 80 characters')
  - (735, 'Line exceeds 80 characters')
  - (741, 'Line exceeds 80 characters')
  - (742, 'Line exceeds 80 characters')
  - (744, 'Hardcoded string found')
  - (745, 'Hardcoded string found')
  - (746, 'Hardcoded string found')
  - (747, 'Hardcoded string found')
  - (750, 'Line exceeds 80 characters')
  - (752, 'Line exceeds 80 characters')
  - (753, 'Line exceeds 80 characters')
  - (755, 'Hardcoded string found')
  - (756, 'Hardcoded string found')
  - (757, 'Hardcoded string found')
  - (758, 'Hardcoded string found')
  - (763, 'Line exceeds 80 characters')
  - (764, 'Line exceeds 80 characters')
  - (766, 'Hardcoded string found')
  - (767, 'Hardcoded string found')
  - (768, 'Hardcoded string found')
  - (773, 'Line exceeds 80 characters')
  - (774, 'Line exceeds 80 characters')
  - (776, 'Hardcoded string found')
  - (777, 'Hardcoded string found')
  - (782, 'Line exceeds 80 characters')
  - (783, 'Line exceeds 80 characters')
  - (785, 'Hardcoded string found')
  - (790, 'Line exceeds 80 characters')
  - (791, 'Line exceeds 80 characters')
  - (793, 'Hardcoded string found')
  - (794, 'Hardcoded string found')
  - (799, 'Line exceeds 80 characters')
  - (800, 'Line exceeds 80 characters')
  - (802, 'Hardcoded string found')
  - (803, 'Hardcoded string found')
  - (808, 'Line exceeds 80 characters')
  - (809, 'Line exceeds 80 characters')
  - (811, 'Hardcoded string found')
  - (812, 'Hardcoded string found')
  - (813, 'Hardcoded string found')
  - (814, 'Hardcoded string found')
  - (819, 'Line exceeds 80 characters')
  - (820, 'Line exceeds 80 characters')
  - (822, 'Hardcoded string found')
  - (823, 'Hardcoded string found')
  - (824, 'Hardcoded string found')
  - (829, 'Line exceeds 80 characters')
  - (830, 'Line exceeds 80 characters')
  - (832, 'Hardcoded string found')
  - (833, 'Hardcoded string found')
  - (834, 'Hardcoded string found')
  - (839, 'Line exceeds 80 characters')
  - (840, 'Line exceeds 80 characters')
  - (842, 'Hardcoded string found')
  - (843, 'Hardcoded string found')
  - (848, 'Line exceeds 80 characters')
  - (849, 'Line exceeds 80 characters')
  - (851, 'Hardcoded string found')
  - (856, 'Line exceeds 80 characters')
  - (857, 'Line exceeds 80 characters')
  - (864, 'Line exceeds 80 characters')
  - (866, 'Hardcoded string found')
  - (867, 'Hardcoded string found')
  - (872, 'Line exceeds 80 characters')
  - (873, 'Line exceeds 80 characters')
  - (875, 'Hardcoded string found')
  - (876, 'Hardcoded string found')
  - (881, 'Line exceeds 80 characters')
  - (882, 'Line exceeds 80 characters')
  - (884, 'Hardcoded string found')
  - (885, 'Hardcoded string found')
  - (886, 'Hardcoded string found')
  - (887, 'Hardcoded string found')
  - (888, 'Hardcoded string found')
  - (889, 'Hardcoded string found')
  - (894, 'Line exceeds 80 characters')
  - (895, 'Line exceeds 80 characters')
  - (897, 'Hardcoded string found')
  - (898, 'Hardcoded string found')
  - (899, 'Hardcoded string found')
  - (900, 'Hardcoded string found')
  - (901, 'Hardcoded string found')
  - (902, 'Hardcoded string found')
  - (908, 'Line exceeds 80 characters')
  - (909, 'Line exceeds 80 characters')
  - (911, 'Hardcoded string found')
  - (916, 'Line exceeds 80 characters')
  - (917, 'Line exceeds 80 characters')
  - (919, 'Hardcoded string found')
  - (924, 'Line exceeds 80 characters')
  - (925, 'Line exceeds 80 characters')
  - (927, 'Hardcoded string found')
  - (928, 'Hardcoded string found')
  - (929, 'Hardcoded string found')
  - (934, 'Line exceeds 80 characters')
  - (935, 'Line exceeds 80 characters')
  - (937, 'Hardcoded string found')
  - (938, 'Hardcoded string found')
  - (939, 'Hardcoded string found')
  - (940, 'Hardcoded string found')
  - (945, 'Line exceeds 80 characters')
  - (946, 'Line exceeds 80 characters')
  - (948, 'Hardcoded string found')
  - (953, 'Line exceeds 80 characters')
  - (954, 'Line exceeds 80 characters')
  - (956, 'Hardcoded string found')
  - (961, 'Line exceeds 80 characters')
  - (962, 'Line exceeds 80 characters')
  - (964, 'Hardcoded string found')
  - (965, 'Hardcoded string found')
  - (970, 'Line exceeds 80 characters')
  - (971, 'Line exceeds 80 characters')
  - (973, 'Hardcoded string found')
  - (978, 'Line exceeds 80 characters')
  - (979, 'Line exceeds 80 characters')
  - (981, 'Hardcoded string found')
  - (983, 'Line exceeds 80 characters')
  - (985, 'Line exceeds 80 characters')
  - (986, 'Line exceeds 80 characters')
  - (988, 'Hardcoded string found')
  - (993, 'Line exceeds 80 characters')
  - (994, 'Line exceeds 80 characters')
  - (996, 'Hardcoded string found')
  - (997, 'Hardcoded string found')
  - (998, 'Hardcoded string found')
  - (999, 'Hardcoded string found')
  - (1000, 'Hardcoded string found')
  - (1001, 'Hardcoded string found')
  - (1002, 'Hardcoded string found')
  - (1007, 'Line exceeds 80 characters')
  - (1008, 'Line exceeds 80 characters')
  - (1010, 'Hardcoded string found')
  - (1011, 'Hardcoded string found')
  - (1012, 'Hardcoded string found')
  - (1018, 'Line exceeds 80 characters')
  - (1024, 'Line exceeds 80 characters')
  - (1025, 'Line exceeds 80 characters')
  - (1027, 'Hardcoded string found')
  - (1028, 'Hardcoded string found')
  - (1033, 'Line exceeds 80 characters')
  - (1034, 'Line exceeds 80 characters')
  - (1036, 'Hardcoded string found')
  - (1041, 'Line exceeds 80 characters')
  - (1042, 'Line exceeds 80 characters')
  - (1048, 'Line exceeds 80 characters')
  - (1049, 'Line exceeds 80 characters')
  - (1055, 'Line exceeds 80 characters')
  - (1056, 'Line exceeds 80 characters')
  - (1058, 'Hardcoded string found')
  - (1063, 'Line exceeds 80 characters')
  - (1064, 'Line exceeds 80 characters')
  - (1070, 'Line exceeds 80 characters')
  - (1071, 'Line exceeds 80 characters')
  - (1073, 'Hardcoded string found')
  - (1074, 'Hardcoded string found')
  - (1075, 'Hardcoded string found')
  - (1081, 'Line exceeds 80 characters')
  - (1082, 'Line exceeds 80 characters')
  - (1084, 'Hardcoded string found')
  - (1085, 'Hardcoded string found')
  - (1086, 'Hardcoded string found')
  - (1087, 'Hardcoded string found')
  - (1088, 'Hardcoded string found')
  - (1089, 'Hardcoded string found')
  - (1094, 'Line exceeds 80 characters')
  - (1095, 'Line exceeds 80 characters')
  - (1097, 'Hardcoded string found')
  - (1098, 'Hardcoded string found')
  - (1103, 'Line exceeds 80 characters')
  - (1104, 'Line exceeds 80 characters')
  - (1110, 'Line exceeds 80 characters')
  - (1111, 'Line exceeds 80 characters')
  - (1113, 'Hardcoded string found')
  - (1118, 'Line exceeds 80 characters')
  - (1119, 'Line exceeds 80 characters')
  - (1121, 'Hardcoded string found')
  - (1122, 'Hardcoded string found')
  - (1127, 'Line exceeds 80 characters')
  - (1128, 'Line exceeds 80 characters')
  - (1130, 'Hardcoded string found')
  - (1131, 'Hardcoded string found')
  - (1132, 'Hardcoded string found')
  - (1133, 'Hardcoded string found')
  - (1134, 'Hardcoded string found')
  - (1135, 'Hardcoded string found')
  - (1136, 'Hardcoded string found')
  - (1141, 'Line exceeds 80 characters')
  - (1142, 'Line exceeds 80 characters')
  - (1149, 'Line exceeds 80 characters')
  - (1151, 'Hardcoded string found')
  - (1156, 'Line exceeds 80 characters')
  - (1157, 'Line exceeds 80 characters')
  - (1159, 'Hardcoded string found')
  - (1160, 'Hardcoded string found')
  - (1165, 'Line exceeds 80 characters')
  - (1167, 'Hardcoded string found')
  - (1174, 'Line exceeds 80 characters')
  - (1176, 'Hardcoded string found')
  - (1177, 'Hardcoded string found')
  - (1179, 'Line exceeds 80 characters')
  - (1180, 'Line exceeds 80 characters')
  - (1183, 'Line exceeds 80 characters')
  - (1189, 'Line exceeds 80 characters')
  - (1190, 'Line exceeds 80 characters')
  - (1194, 'Line exceeds 80 characters')
  - (1195, 'Line exceeds 80 characters')
  - (1199, 'Line exceeds 80 characters')
  - (1200, 'Line exceeds 80 characters')
  - (1208, 'Line exceeds 80 characters')
  - (1209, 'Line exceeds 80 characters')
  - (1213, 'Line exceeds 80 characters')
  - (1214, 'Line exceeds 80 characters')
  - (1218, 'Line exceeds 80 characters')
  - (1226, 'Line exceeds 80 characters')
  - (1232, 'Line exceeds 80 characters')
  - (1233, 'Line exceeds 80 characters')
  - (1238, 'Line exceeds 80 characters')
  - (1242, 'Line exceeds 80 characters')
  - (1251, 'Line exceeds 80 characters')
  - (1257, 'Line exceeds 80 characters')

**Comment by brandonabeal110** [comment]
I got it.
