### ISSUE TITLE
Issue-Add Solana logo

### ISSUE THREAD

**Issue by kazupot7** [kazupot7/token-creator#29]
Automated Review Comments
Issues in README.md:
  - (28, 'Line exceeds 80 characters')
Issues in src/components/builton.svg:
  - (2, 'Line exceeds 80 characters')
  - (2, 'Hardcoded string found')
  - (3, 'Line exceeds 80 characters')
  - (4, 'Line exceeds 80 characters')
  - (5, 'Line exceeds 80 characters')
  - (6, 'Line exceeds 80 characters')
  - (6, 'Hardcoded string found')
  - (7, 'Line exceeds 80 characters')
  - (7, 'Hardcoded string found')
  - (8, 'Line exceeds 80 characters')
  - (8, 'Hardcoded string found')
  - (9, 'Line exceeds 80 characters')
  - (9, 'Hardcoded string found')
  - (10, 'Line exceeds 80 characters')
  - (10, 'Hardcoded string found')
  - (11, 'Line exceeds 80 characters')
  - (11, 'Hardcoded string found')
  - (12, 'Line exceeds 80 characters')
  - (13, 'Line exceeds 80 characters')
  - (15, 'Line exceeds 80 characters')
  - (16, 'Line exceeds 80 characters')
  - (17, 'Line exceeds 80 characters')
  - (18, 'Line exceeds 80 characters')
Issues in src/views/home/index.tsx:
  - (6, 'Hardcoded string found')

**Comment by Zeusofsky** [comment]
I got it.
