### ISSUE TITLE
Issue-add missing @ant-design/icons dependency

### ISSUE THREAD

**Issue by kazupot7** [kazupot7/token-creator#37]
Automated Review Comments
Issues in README.md:
  - (7, 'Line exceeds 80 characters')
Issues in package.json:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (27, 'Hardcoded string found')
  - (28, 'Hardcoded string found')
  - (30, 'Hardcoded string found')
  - (44, 'Hardcoded string found')

**Comment by brandonabeal110** [comment]
I got it.
