### ISSUE TITLE
Issue-feat: initial scaffold

### ISSUE THREAD

**Issue by kazupot7** [kazupot7/token-creator#4]
Automated Review Comments
Issues in .gitignore:
  - (2, 'Line exceeds 80 characters')
Issues in package.json:
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (27, 'Hardcoded string found')
  - (28, 'Hardcoded string found')
  - (34, 'Hardcoded string found')
  - (35, 'Hardcoded string found')
  - (37, 'Hardcoded string found')
  - (38, 'Hardcoded string found')
  - (39, 'Hardcoded string found')
  - (40, 'Hardcoded string found')
  - (41, 'Hardcoded string found')
  - (43, 'Line exceeds 80 characters')
  - (46, 'Hardcoded string found')
  - (47, 'Hardcoded string found')
  - (51, 'Hardcoded string found')
  - (52, 'Hardcoded string found')
  - (54, 'Hardcoded string found')
  - (55, 'Hardcoded string found')
  - (57, 'Hardcoded string found')
  - (60, 'Hardcoded string found')
  - (66, 'Hardcoded string found')
  - (67, 'Hardcoded string found')
  - (68, 'Hardcoded string found')
  - (70, 'Hardcoded string found')
  - (71, 'Hardcoded string found')
  - (83, 'Hardcoded string found')
Issues in public/index.html:
  - (3, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (12, 'Line exceeds 80 characters')
  - (14, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (52, 'Hardcoded string found')
  - (53, 'Line exceeds 80 characters')
  - (54, 'Line exceeds 80 characters')
  - (55, 'Hardcoded string found')
  - (61, 'Hardcoded string found')
Issues in public/manifest.json:
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
Issues in src/App.less:
  - (10, 'Line exceeds 80 characters')
Issues in src/App.test.tsx:
  - (2, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
Issues in src/App.tsx:
  - (2, 'Hardcoded string found')
Issues in src/actions/account.ts:
  - (149, 'TODO found')
  - (149, 'Line exceeds 80 characters')
Issues in src/components/AppBar/index.tsx:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (27, 'Hardcoded string found')
  - (30, 'Hardcoded string found')
  - (33, 'Hardcoded string found')
  - (34, 'Hardcoded string found')
  - (35, 'Hardcoded string found')
Issues in src/components/ConnectButton/index.tsx:
  - (2, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
Issues in src/components/CurrentUserBadge/index.tsx:
  - (2, 'Hardcoded string found')
  - (28, 'Hardcoded string found')
Issues in src/components/ExplorerLink/index.tsx:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
Issues in src/components/Icons/info.tsx:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
Issues in src/components/Identicon/index.tsx:
  - (2, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (28, 'Hardcoded string found')
Issues in src/components/Input/numeric.tsx:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (25, 'Line exceeds 80 characters')
Issues in src/components/Layout/index.tsx:
  - (2, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (31, 'Hardcoded string found')
  - (34, 'Hardcoded string found')
  - (35, 'Hardcoded string found')
  - (41, 'Hardcoded string found')
  - (48, 'Hardcoded string found')
  - (56, 'Hardcoded string found')
  - (60, 'Hardcoded string found')
  - (87, 'Hardcoded string found')
  - (92, 'Hardcoded string found')
  - (95, 'Hardcoded string found')
  - (103, 'Hardcoded string found')
  - (106, 'Hardcoded string found')
Issues in src/components/Settings/index.tsx:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (27, 'Hardcoded string found')
Issues in src/components/TokenDisplay/index.tsx:
  - (2, 'Hardcoded string found')
  - (32, 'Hardcoded string found')
  - (33, 'Hardcoded string found')
  - (37, 'Hardcoded string found')
  - (47, 'Hardcoded string found')
Issues in src/components/TokenIcon/index.tsx:
  - (3, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (32, 'Hardcoded string found')
  - (61, 'Hardcoded string found')

**Comment by williamddobson3** [comment]
I got it.
