### ISSUE TITLE
Issue-Merge pull request #3 from Arrowana/readme-dir-structure-fix

Fix readme for clear structure

### ISSUE THREAD

**Issue by kazupot7** [kazupot7/token-creator#41]
Automated Review Comments
Issues in README.md:
  - (7, 'Line exceeds 80 characters')
Issues in package.json:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (26, 'Hardcoded string found')
  - (27, 'Hardcoded string found')
  - (28, 'Hardcoded string found')
  - (34, 'Hardcoded string found')
  - (35, 'Hardcoded string found')
  - (37, 'Hardcoded string found')
  - (39, 'Hardcoded string found')
  - (53, 'Hardcoded string found')

**Comment by williamddobson3** [comment]
I got it.
