### ISSUE TITLE
Issue-Merge pull request #4 from johnrees/dependencies-cleanup

Add a missing dependency, remove some unused ones

### ISSUE THREAD

**Issue by kazupot7** [kazupot7/token-creator#43]
Automated Review Comments
Issues in package.json:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (26, 'Hardcoded string found')
  - (27, 'Hardcoded string found')
  - (28, 'Hardcoded string found')
  - (34, 'Hardcoded string found')
  - (35, 'Hardcoded string found')
  - (37, 'Hardcoded string found')
  - (39, 'Hardcoded string found')
  - (53, 'Hardcoded string found')
Issues in src/views/home/index.tsx:
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (13, 'Hardcoded string found')

**Comment by williamddobson3** [comment]
I got it.
