### ISSUE TITLE
Issue-fix: issue with useUserBalance

### ISSUE THREAD

**Issue by kazupot7** [kazupot7/token-creator#45]
Automated Review Comments
Issues in README.md:
  - (19, 'Line exceeds 80 characters')
  - (20, 'Line exceeds 80 characters')
  - (33, 'Line exceeds 80 characters')
Issues in package.json:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (29, 'Hardcoded string found')
  - (30, 'Hardcoded string found')
  - (31, 'Hardcoded string found')
  - (37, 'Hardcoded string found')
  - (38, 'Hardcoded string found')
  - (40, 'Hardcoded string found')
  - (42, 'Hardcoded string found')
  - (56, 'Hardcoded string found')
Issues in src/contexts/accounts.tsx:
  - (17, 'Line exceeds 80 characters')
Issues in src/views/home/index.tsx:
  - (1, 'Line exceeds 80 characters')
  - (21, 'Hardcoded string found')

**Comment by martinjbrown776** [comment]
I got it.
