### ISSUE TITLE
Issue-Merge branch 'main' of https://github.com/solana-labs/dapp-scaffold into main

### ISSUE THREAD

**Issue by kazupot7** [kazupot7/token-creator#47]
Automated Review Comments
Issues in README.md:
  - (7, 'Line exceeds 80 characters')
Issues in package.json:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
  - (25, 'Hardcoded string found')
  - (26, 'Hardcoded string found')
  - (32, 'Hardcoded string found')
  - (33, 'Hardcoded string found')
  - (35, 'Hardcoded string found')
  - (37, 'Hardcoded string found')
  - (51, 'Hardcoded string found')

**Comment by williamddobson3** [comment]
I got it.
