### ISSUE TITLE
Issue-feat: use token-list

### ISSUE THREAD

**Issue by kazupot7** [kazupot7/token-creator#52]
Automated Review Comments
Issues in src/contexts/accounts.tsx:
  - (17, 'Hardcoded string found')
  - (34, 'Hardcoded string found')
  - (63, 'Hardcoded string found')
Issues in src/contexts/connection.tsx:
  - (12, 'Hardcoded string found')
  - (20, 'Line exceeds 80 characters')
  - (31, 'Hardcoded string found')
  - (32, 'Hardcoded string found')
  - (36, 'Hardcoded string found')
  - (37, 'Hardcoded string found')
  - (41, 'Hardcoded string found')
  - (45, 'Hardcoded string found')
  - (46, 'Hardcoded string found')
  - (47, 'Hardcoded string found')
  - (62, 'Line exceeds 80 characters')
  - (63, 'Hardcoded string found')
  - (71, 'Line exceeds 80 characters')
  - (91, 'Line exceeds 80 characters')
  - (99, 'Hardcoded string found')
  - (106, 'Line exceeds 80 characters')
  - (106, 'Hardcoded string found')
Issues in src/utils/utils.ts:
  - (18, 'Hardcoded string found')
Issues in src/views/home/index.tsx:
  - (1, 'Hardcoded string found')
  - (2, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
  - (25, 'Line exceeds 80 characters')
Issues in yarn.lock:
  - (7, 'Line exceeds 80 characters')
  - (8, 'Line exceeds 80 characters')
  - (11, 'Line exceeds 80 characters')
  - (12, 'Line exceeds 80 characters')
  - (14, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (20, 'Line exceeds 80 characters')
  - (21, 'Line exceeds 80 characters')
  - (25, 'Line exceeds 80 characters')
  - (26, 'Line exceeds 80 characters')
  - (28, 'Hardcoded string found')
  - (29, 'Hardcoded string found')
  - (30, 'Hardcoded string found')
  - (37, 'Line exceeds 80 characters')
  - (44, 'Line exceeds 80 characters')
  - (45, 'Line exceeds 80 characters')
  - (48, 'Line exceeds 80 characters')
  - (49, 'Line exceeds 80 characters')
  - (51, 'Hardcoded string found')
  - (52, 'Hardcoded string found')
  - (53, 'Hardcoded string found')
  - (54, 'Hardcoded string found')
  - (55, 'Hardcoded string found')
  - (56, 'Hardcoded string found')
  - (57, 'Hardcoded string found')
  - (76, 'Line exceeds 80 characters')
  - (77, 'Line exceeds 80 characters')
  - (84, 'Line exceeds 80 characters')
  - (85, 'Line exceeds 80 characters')
  - (87, 'Hardcoded string found')
  - (88, 'Hardcoded string found')
  - (96, 'Line exceeds 80 characters')
  - (98, 'Line exceeds 80 characters')
  - (99, 'Line exceeds 80 characters')
  - (103, 'Line exceeds 80 characters')
  - (104, 'Line exceeds 80 characters')
  - (108, 'Line exceeds 80 characters')
  - (109, 'Line exceeds 80 characters')
  - (115, 'Line exceeds 80 characters')
  - (116, 'Line exceeds 80 characters')
  - (118, 'Hardcoded string found')
  - (123, 'Line exceeds 80 characters')
  - (124, 'Line exceeds 80 characters')
  - (126, 'Hardcoded string found')
  - (131, 'Line exceeds 80 characters')
  - (132, 'Line exceeds 80 characters')
  - (134, 'Hardcoded string found')
  - (139, 'Line exceeds 80 characters')
  - (140, 'Line exceeds 80 characters')
  - (142, 'Hardcoded string found')
  - (147, 'Line exceeds 80 characters')
  - (148, 'Line exceeds 80 characters')
  - (150, 'Hardcoded string found')
  - (151, 'Hardcoded string found')
  - (152, 'Hardcoded string found')
  - (153, 'Hardcoded string found')
  - (154, 'Hardcoded string found')
  - (161, 'Line exceeds 80 characters')
  - (162, 'Line exceeds 80 characters')
  - (172, 'Line exceeds 80 characters')
  - (173, 'Line exceeds 80 characters')
  - (177, 'Line exceeds 80 characters')
  - (179, 'Hardcoded string found')
  - (180, 'Hardcoded string found')
  - (184, 'Line exceeds 80 characters')
  - (185, 'Line exceeds 80 characters')
  - (189, 'Line exceeds 80 characters')
  - (191, 'Line exceeds 80 characters')
  - (192, 'Line exceeds 80 characters')
  - (196, 'Line exceeds 80 characters')
  - (197, 'Line exceeds 80 characters')
  - (199, 'Hardcoded string found')
  - (204, 'Line exceeds 80 characters')
  - (205, 'Line exceeds 80 characters')
  - (209, 'Line exceeds 80 characters')
  - (216, 'Line exceeds 80 characters')
  - (217, 'Line exceeds 80 characters')
  - (219, 'Hardcoded string found')
  - (226, 'Line exceeds 80 characters')
  - (228, 'Line exceeds 80 characters')
  - (229, 'Line exceeds 80 characters')
  - (233, 'Line exceeds 80 characters')
  - (234, 'Line exceeds 80 characters')
  - (241, 'Line exceeds 80 characters')
  - (242, 'Line exceeds 80 characters')
  - (248, 'Line exceeds 80 characters')
  - (249, 'Line exceeds 80 characters')
  - (256, 'Line exceeds 80 characters')
  - (261, 'Line exceeds 80 characters')
  - (264, 'Line exceeds 80 characters')
  - (265, 'Line exceeds 80 characters')
  - (267, 'Line exceeds 80 characters')
  - (273, 'Line exceeds 80 characters')
  - (274, 'Line exceeds 80 characters')
  - (281, 'Line exceeds 80 characters')
  - (286, 'Line exceeds 80 characters')
  - (288, 'Line exceeds 80 characters')
  - (294, 'Line exceeds 80 characters')
  - (295, 'Line exceeds 80 characters')
  - (297, 'Line exceeds 80 characters')
  - (302, 'Line exceeds 80 characters')
  - (303, 'Line exceeds 80 characters')
  - (307, 'Line exceeds 80 characters')
  - (314, 'Line exceeds 80 characters')
  - (315, 'Line exceeds 80 characters')
  - (319, 'Line exceeds 80 characters')
  - (327, 'Line exceeds 80 characters')
  - (328, 'Line exceeds 80 characters')
  - (330, 'Line exceeds 80 characters')
  - (331, 'Line exceeds 80 characters')
  - (336, 'Line exceeds 80 characters')
  - (337, 'Line exceeds 80 characters')
  - (342, 'Line exceeds 80 characters')
  - (345, 'Line exceeds 80 characters')
  - (346, 'Line exceeds 80 characters')
  - (353, 'Line exceeds 80 characters')
  - (354, 'Line exceeds 80 characters')
  - (358, 'Line exceeds 80 characters')
  - (365, 'Line exceeds 80 characters')
  - (366, 'Line exceeds 80 characters')
  - (370, 'Line exceeds 80 characters')
  - (377, 'Line exceeds 80 characters')
  - (378, 'Line exceeds 80 characters')
  - (380, 'Hardcoded string found')
  - (385, 'Line exceeds 80 characters')
  - (386, 'Line exceeds 80 characters')
  - (394, 'Line exceeds 80 characters')
  - (396, 'Line exceeds 80 characters')
  - (401, 'Line exceeds 80 characters')
  - (406, 'Line exceeds 80 characters')
  - (413, 'Line exceeds 80 characters')
  - (414, 'Line exceeds 80 characters')
  - (420, 'Line exceeds 80 characters')
  - (422, 'Line exceeds 80 characters')
  - (427, 'Line exceeds 80 characters')
  - (428, 'Line exceeds 80 characters')
  - (432, 'Line exceeds 80 characters')
  - (434, 'Line exceeds 80 characters')
  - (435, 'Line exceeds 80 characters')
  - (439, 'Line exceeds 80 characters')
  - (440, 'Line exceeds 80 characters')
  - (442, 'Hardcoded string found')
  - (447, 'Line exceeds 80 characters')
  - (448, 'Line exceeds 80 characters')
  - (455, 'Line exceeds 80 characters')
  - (456, 'Line exceeds 80 characters')
  - (458, 'Line exceeds 80 characters')
  - (463, 'Line exceeds 80 characters')
  - (464, 'Line exceeds 80 characters')
  - (468, 'Line exceeds 80 characters')
  - (473, 'Line exceeds 80 characters')
  - (476, 'Line exceeds 80 characters')
  - (477, 'Line exceeds 80 characters')
  - (479, 'Line exceeds 80 characters')
  - (480, 'Line exceeds 80 characters')
  - (484, 'Line exceeds 80 characters')
  - (485, 'Line exceeds 80 characters')
  - (489, 'Line exceeds 80 characters')
  - (496, 'Line exceeds 80 characters')
  - (497, 'Line exceeds 80 characters')
  - (504, 'Line exceeds 80 characters')
  - (506, 'Line exceeds 80 characters')
  - (507, 'Line exceeds 80 characters')
  - (511, 'Line exceeds 80 characters')
  - (512, 'Line exceeds 80 characters')
  - (518, 'Line exceeds 80 characters')
  - (519, 'Line exceeds 80 characters')
  - (521, 'Hardcoded string found')
  - (522, 'Hardcoded string found')
  - (523, 'Hardcoded string found')
  - (524, 'Hardcoded string found')
  - (525, 'Hardcoded string found')
  - (526, 'Hardcoded string found')
  - (534, 'Line exceeds 80 characters')
  - (536, 'Line exceeds 80 characters')
  - (538, 'Line exceeds 80 characters')
  - (539, 'Line exceeds 80 characters')
  - (543, 'Line exceeds 80 characters')
  - (544, 'Line exceeds 80 characters')
  - (553, 'Line exceeds 80 characters')
  - (554, 'Line exceeds 80 characters')
  - (556, 'Hardcoded string found')
  - (566, 'Line exceeds 80 characters')
  - (573, 'Line exceeds 80 characters')
  - (574, 'Line exceeds 80 characters')
  - (576, 'Hardcoded string found')
  - (589, 'Line exceeds 80 characters')
  - (596, 'Line exceeds 80 characters')
  - (597, 'Line exceeds 80 characters')
  - (601, 'Line exceeds 80 characters')
  - (603, 'Line exceeds 80 characters')
  - (604, 'Line exceeds 80 characters')
  - (608, 'Line exceeds 80 characters')
  - (609, 'Line exceeds 80 characters')
  - (613, 'Line exceeds 80 characters')
  - (620, 'Line exceeds 80 characters')
  - (621, 'Line exceeds 80 characters')
  - (625, 'Line exceeds 80 characters')
  - (632, 'Line exceeds 80 characters')
  - (633, 'Line exceeds 80 characters')
  - (637, 'Line exceeds 80 characters')
  - (638, 'Line exceeds 80 characters')
  - (644, 'Line exceeds 80 characters')

**Comment by christianagalindo7** [comment]
I got it.
