### ISSUE TITLE
Issue-feat: add useUserTotalBalance

### ISSUE THREAD

**Issue by kazupot7** [kazupot7/token-creator#54]
Automated Review Comments
Issues in src/contexts/accounts.tsx:
  - (17, 'Line exceeds 80 characters')
Issues in src/contexts/market.tsx:
  - (1, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (30, 'Line exceeds 80 characters')
Issues in src/hooks/useUserTotalBalance.ts:
  - (2, 'Hardcoded string found')
  - (21, 'Line exceeds 80 characters')
Issues in src/views/home/index.tsx:
  - (20, 'Hardcoded string found')
  - (25, 'Hardcoded string found')
  - (26, 'Line exceeds 80 characters')
Issues in yarn.lock:
  - (2, 'Line exceeds 80 characters')
  - (3, 'Line exceeds 80 characters')
  - (7, 'Line exceeds 80 characters')
  - (8, 'Line exceeds 80 characters')
  - (11, 'Line exceeds 80 characters')
  - (12, 'Line exceeds 80 characters')
  - (14, 'Hardcoded string found')

**Comment by Zeusofsky** [comment]
I got it.
