### ISSUE TITLE
Issue-feat: update references

### ISSUE THREAD

**Issue by kazupot7** [kazupot7/token-creator#63]
Automated Review Comments
Issues in yarn.lock:
  - (7, 'Line exceeds 80 characters')
  - (8, 'Line exceeds 80 characters')
  - (14, 'Line exceeds 80 characters')
  - (16, 'Line exceeds 80 characters')
  - (17, 'Line exceeds 80 characters')
  - (21, 'Line exceeds 80 characters')
  - (22, 'Line exceeds 80 characters')
  - (25, 'Line exceeds 80 characters')
  - (26, 'Line exceeds 80 characters')
  - (28, 'Hardcoded string found')
  - (34, 'Line exceeds 80 characters')
  - (35, 'Line exceeds 80 characters')
  - (38, 'Line exceeds 80 characters')
  - (39, 'Line exceeds 80 characters')
  - (44, 'Line exceeds 80 characters')
  - (45, 'Line exceeds 80 characters')
  - (49, 'Line exceeds 80 characters')
  - (50, 'Line exceeds 80 characters')
  - (53, 'Line exceeds 80 characters')
  - (54, 'Line exceeds 80 characters')
  - (61, 'Line exceeds 80 characters')
  - (62, 'Line exceeds 80 characters')
  - (65, 'Line exceeds 80 characters')
  - (66, 'Line exceeds 80 characters')
  - (68, 'Hardcoded string found')
  - (69, 'Hardcoded string found')
  - (70, 'Hardcoded string found')
  - (79, 'Line exceeds 80 characters')
  - (80, 'Line exceeds 80 characters')
  - (83, 'Line exceeds 80 characters')
  - (84, 'Line exceeds 80 characters')
  - (86, 'Hardcoded string found')
  - (87, 'Hardcoded string found')
  - (89, 'Hardcoded string found')
  - (98, 'Line exceeds 80 characters')
  - (99, 'Line exceeds 80 characters')
  - (101, 'Hardcoded string found')
  - (119, 'Line exceeds 80 characters')
  - (120, 'Line exceeds 80 characters')
  - (123, 'Line exceeds 80 characters')
  - (124, 'Line exceeds 80 characters')
  - (126, 'Hardcoded string found')
  - (140, 'Line exceeds 80 characters')
  - (141, 'Line exceeds 80 characters')
  - (144, 'Line exceeds 80 characters')
  - (145, 'Line exceeds 80 characters')
  - (147, 'Hardcoded string found')
  - (148, 'Hardcoded string found')
  - (174, 'Line exceeds 80 characters')
  - (175, 'Line exceeds 80 characters')
  - (179, 'Line exceeds 80 characters')
  - (180, 'Line exceeds 80 characters')
  - (184, 'Line exceeds 80 characters')
  - (186, 'Line exceeds 80 characters')
  - (191, 'Line exceeds 80 characters')
  - (192, 'Line exceeds 80 characters')
  - (200, 'Line exceeds 80 characters')
  - (201, 'Line exceeds 80 characters')
  - (204, 'Line exceeds 80 characters')
  - (205, 'Line exceeds 80 characters')
  - (214, 'Line exceeds 80 characters')
  - (215, 'Line exceeds 80 characters')
  - (222, 'Line exceeds 80 characters')
  - (223, 'Line exceeds 80 characters')
  - (231, 'Line exceeds 80 characters')
  - (232, 'Line exceeds 80 characters')
  - (238, 'Line exceeds 80 characters')
  - (239, 'Line exceeds 80 characters')
  - (242, 'Line exceeds 80 characters')
  - (243, 'Line exceeds 80 characters')
  - (254, 'Line exceeds 80 characters')
  - (255, 'Line exceeds 80 characters')
  - (262, 'Line exceeds 80 characters')
  - (263, 'Line exceeds 80 characters')
  - (265, 'Hardcoded string found')
  - (266, 'Hardcoded string found')
  - (267, 'Hardcoded string found')
  - (268, 'Hardcoded string found')
  - (279, 'Line exceeds 80 characters')
  - (286, 'Line exceeds 80 characters')
  - (287, 'Line exceeds 80 characters')
  - (291, 'Line exceeds 80 characters')
  - (293, 'Line exceeds 80 characters')
  - (294, 'Line exceeds 80 characters')
  - (299, 'Line exceeds 80 characters')
  - (300, 'Line exceeds 80 characters')
  - (307, 'Line exceeds 80 characters')
  - (308, 'Line exceeds 80 characters')
  - (312, 'Line exceeds 80 characters')

**Comment by christianagalindo7** [comment]
I got it.
