### ISSUE TITLE
Issue-Update to 1.6.7

### ISSUE THREAD

**Issue by kazupot7** [kazupot7/token-creator#65]
Automated Review Comments
Issues in README.md:
  - (5, 'Line exceeds 80 characters')
  - (6, 'Line exceeds 80 characters')
Issues in program/Cargo.lock:
  - (12, 'Hardcoded string found')
  - (14, 'Line exceeds 80 characters')
  - (38, 'Line exceeds 80 characters')
  - (41, 'Hardcoded string found')
  - (50, 'Hardcoded string found')
  - (65, 'Hardcoded string found')
  - (71, 'Hardcoded string found')
  - (125, 'Hardcoded string found')
  - (131, 'Hardcoded string found')
  - (164, 'Hardcoded string found')
  - (173, 'Hardcoded string found')
  - (177, 'Hardcoded string found')
  - (196, 'Hardcoded string found')
  - (212, 'Hardcoded string found')
  - (216, 'Hardcoded string found')
  - (227, 'Hardcoded string found')
  - (233, 'Hardcoded string found')
  - (245, 'Hardcoded string found')
  - (277, 'Hardcoded string found')
  - (278, 'Hardcoded string found')
  - (317, 'Hardcoded string found')
  - (328, 'Hardcoded string found')
  - (330, 'Hardcoded string found')
  - (348, 'Hardcoded string found')
  - (351, 'Hardcoded string found')
  - (357, 'Hardcoded string found')
  - (358, 'Hardcoded string found')
  - (360, 'Hardcoded string found')
  - (361, 'Hardcoded string found')
  - (365, 'Hardcoded string found')
  - (379, 'Hardcoded string found')
  - (384, 'Hardcoded string found')
  - (385, 'Hardcoded string found')
  - (386, 'Hardcoded string found')
  - (391, 'Hardcoded string found')
  - (401, 'Hardcoded string found')
  - (411, 'Hardcoded string found')
  - (421, 'Hardcoded string found')
  - (428, 'Hardcoded string found')
  - (434, 'Hardcoded string found')
  - (435, 'Hardcoded string found')
  - (439, 'Hardcoded string found')
  - (456, 'Hardcoded string found')
  - (470, 'Hardcoded string found')
  - (478, 'Hardcoded string found')
  - (496, 'Hardcoded string found')
  - (498, 'Hardcoded string found')
  - (499, 'Hardcoded string found')
  - (500, 'Hardcoded string found')
  - (501, 'Hardcoded string found')
  - (519, 'Hardcoded string found')
  - (520, 'Hardcoded string found')
  - (524, 'Hardcoded string found')
  - (540, 'Hardcoded string found')
  - (542, 'Hardcoded string found')
  - (543, 'Hardcoded string found')
  - (544, 'Hardcoded string found')
  - (551, 'Hardcoded string found')
  - (553, 'Hardcoded string found')
  - (569, 'Hardcoded string found')
  - (573, 'Hardcoded string found')
  - (601, 'Hardcoded string found')
  - (606, 'Hardcoded string found')
  - (610, 'Hardcoded string found')
  - (622, 'Hardcoded string found')
  - (631, 'Hardcoded string found')
  - (636, 'Hardcoded string found')
  - (650, 'Hardcoded string found')
  - (728, 'Hardcoded string found')
  - (742, 'Hardcoded string found')
  - (768, 'Hardcoded string found')
  - (826, 'Hardcoded string found')
  - (848, 'Hardcoded string found')
  - (857, 'Hardcoded string found')
  - (877, 'Hardcoded string found')
  - (879, 'Hardcoded string found')
  - (895, 'Hardcoded string found')
  - (899, 'Hardcoded string found')
  - (913, 'Hardcoded string found')
  - (929, 'Hardcoded string found')
  - (934, 'Hardcoded string found')
  - (943, 'Hardcoded string found')
  - (944, 'Hardcoded string found')
  - (956, 'Hardcoded string found')
  - (966, 'Hardcoded string found')
  - (971, 'Hardcoded string found')
  - (981, 'Hardcoded string found')
  - (982, 'Hardcoded string found')
  - (983, 'Line exceeds 80 characters')
  - (996, 'Hardcoded string found')
  - (997, 'Hardcoded string found')
  - (1008, 'Hardcoded string found')
  - (1020, 'Hardcoded string found')
  - (1032, 'Hardcoded string found')
  - (1033, 'Hardcoded string found')
  - (1040, 'Hardcoded string found')
  - (1055, 'Hardcoded string found')
  - (1066, 'Hardcoded string found')
  - (1071, 'Hardcoded string found')
  - (1086, 'Hardcoded string found')
  - (1087, 'Hardcoded string found')
  - (1107, 'Hardcoded string found')
  - (1108, 'Hardcoded string found')
  - (1119, 'Hardcoded string found')
  - (1120, 'Hardcoded string found')
  - (1123, 'Hardcoded string found')
  - (1125, 'Hardcoded string found')
  - (1150, 'Hardcoded string found')
  - (1161, 'Hardcoded string found')
  - (1163, 'Hardcoded string found')
  - (1175, 'Hardcoded string found')
  - (1176, 'Hardcoded string found')
  - (1179, 'Hardcoded string found')
  - (1194, 'Hardcoded string found')
  - (1197, 'Hardcoded string found')
  - (1198, 'Hardcoded string found')
  - (1200, 'Hardcoded string found')
  - (1206, 'Hardcoded string found')
  - (1208, 'Hardcoded string found')
  - (1215, 'Hardcoded string found')
  - (1217, 'Hardcoded string found')
  - (1224, 'Hardcoded string found')
  - (1225, 'Hardcoded string found')
  - (1226, 'Hardcoded string found')
  - (1229, 'Hardcoded string found')
  - (1230, 'Hardcoded string found')
  - (1235, 'Hardcoded string found')
  - (1236, 'Hardcoded string found')
  - (1244, 'Hardcoded string found')
  - (1255, 'Hardcoded string found')
  - (1279, 'Hardcoded string found')
  - (1280, 'Hardcoded string found')
  - (1287, 'Hardcoded string found')
  - (1300, 'Hardcoded string found')
  - (1323, 'Hardcoded string found')
  - (1324, 'Hardcoded string found')
  - (1330, 'Hardcoded string found')
  - (1332, 'Hardcoded string found')
  - (1336, 'Hardcoded string found')
  - (1337, 'Hardcoded string found')
  - (1341, 'Hardcoded string found')
  - (1365, 'Hardcoded string found')
  - (1378, 'Hardcoded string found')
  - (1391, 'Hardcoded string found')
  - (1402, 'Hardcoded string found')
  - (1403, 'Hardcoded string found')
  - (1406, 'Hardcoded string found')
  - (1426, 'Hardcoded string found')
  - (1429, 'Hardcoded string found')
  - (1446, 'Hardcoded string found')
  - (1448, 'Hardcoded string found')
  - (1451, 'Hardcoded string found')
  - (1453, 'Hardcoded string found')
  - (1455, 'Hardcoded string found')
  - (1471, 'Hardcoded string found')
  - (1472, 'Hardcoded string found')
  - (1476, 'Hardcoded string found')
  - (1486, 'Hardcoded string found')
  - (1517, 'Hardcoded string found')
  - (1520, 'Hardcoded string found')
  - (1522, 'Hardcoded string found')
  - (1533, 'Hardcoded string found')
  - (1534, 'Hardcoded string found')
  - (1536, 'Hardcoded string found')
  - (1540, 'Hardcoded string found')
  - (1543, 'Hardcoded string found')
  - (1545, 'Hardcoded string found')
  - (1558, 'Hardcoded string found')
  - (1560, 'Hardcoded string found')
  - (1561, 'Hardcoded string found')
  - (1562, 'Hardcoded string found')
  - (1568, 'Hardcoded string found')
  - (1571, 'Hardcoded string found')
  - (1579, 'Hardcoded string found')
  - (1584, 'Hardcoded string found')
  - (1585, 'Hardcoded string found')
  - (1589, 'Hardcoded string found')
  - (1590, 'Hardcoded string found')
  - (1613, 'Hardcoded string found')
  - (1625, 'Hardcoded string found')
  - (1639, 'Hardcoded string found')
  - (1640, 'Hardcoded string found')
  - (1644, 'Hardcoded string found')
  - (1647, 'Hardcoded string found')
  - (1660, 'Hardcoded string found')
  - (1672, 'Hardcoded string found')
  - (1684, 'Hardcoded string found')
  - (1685, 'Hardcoded string found')
  - (1696, 'Hardcoded string found')
  - (1707, 'Hardcoded string found')
  - (1719, 'Hardcoded string found')
  - (1723, 'Hardcoded string found')
  - (1729, 'Hardcoded string found')
  - (1734, 'Hardcoded string found')
  - (1760, 'Hardcoded string found')
  - (1772, 'Hardcoded string found')
  - (1773, 'Hardcoded string found')
  - (1774, 'Line exceeds 80 characters')
  - (1809, 'Hardcoded string found')
  - (1816, 'Hardcoded string found')
  - (1825, 'Hardcoded string found')
  - (1830, 'Hardcoded string found')
  - (1837, 'Hardcoded string found')
  - (1838, 'Hardcoded string found')
  - (1840, 'Hardcoded string found')
  - (1870, 'Hardcoded string found')
  - (1872, 'Hardcoded string found')
  - (1881, 'Hardcoded string found')
  - (1883, 'Hardcoded string found')
  - (1890, 'Hardcoded string found')
  - (1901, 'Hardcoded string found')
  - (1902, 'Hardcoded string found')
  - (1908, 'Hardcoded string found')
  - (1921, 'Hardcoded string found')
  - (1967, 'Hardcoded string found')
  - (1970, 'Hardcoded string found')
  - (1981, 'Hardcoded string found')
  - (1983, 'Hardcoded string found')
  - (1987, 'Hardcoded string found')
  - (1991, 'Hardcoded string found')
  - (2049, 'Hardcoded string found')
  - (2068, 'Hardcoded string found')
  - (2074, 'Hardcoded string found')
  - (2082, 'Hardcoded string found')
  - (2087, 'Hardcoded string found')
  - (2092, 'Hardcoded string found')
  - (2119, 'Hardcoded string found')
  - (2124, 'Hardcoded string found')
  - (2135, 'Hardcoded string found')
  - (2149, 'Hardcoded string found')
  - (2227, 'Hardcoded string found')
  - (2277, 'Hardcoded string found')
  - (2281, 'Hardcoded string found')
  - (2284, 'Hardcoded string found')
  - (2285, 'Hardcoded string found')
  - (2293, 'Hardcoded string found')
  - (2298, 'Hardcoded string found')
  - (2303, 'Hardcoded string found')
  - (2310, 'Hardcoded string found')
  - (2321, 'Hardcoded string found')
  - (2333, 'Hardcoded string found')
  - (2353, 'Line exceeds 80 characters')
  - (2355, 'Hardcoded string found')
  - (2356, 'Hardcoded string found')
  - (2358, 'Hardcoded string found')
  - (2359, 'Hardcoded string found')
Issues in program/Cargo.toml:
  - (1, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (21, 'Hardcoded string found')

**Comment by Muray1008** [comment]
I got it.
