### ISSUE TITLE
Issue-add phantom wallet provider

### ISSUE THREAD

**Issue by kazupot7** [kazupot7/token-creator#77]
Automated Review Comments
Issues in README.md:
  - (19, 'Line exceeds 80 characters')
  - (20, 'Line exceeds 80 characters')
  - (36, 'Line exceeds 80 characters')
  - (43, 'Line exceeds 80 characters')
Issues in package.json:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
  - (31, 'Hardcoded string found')
  - (32, 'Hardcoded string found')
  - (33, 'Hardcoded string found')
  - (39, 'Hardcoded string found')
  - (41, 'Hardcoded string found')
  - (42, 'Hardcoded string found')
  - (43, 'Hardcoded string found')
  - (46, 'Line exceeds 80 characters')
  - (47, 'Hardcoded string found')
  - (49, 'Line exceeds 80 characters')
  - (52, 'Hardcoded string found')
  - (53, 'Hardcoded string found')
  - (56, 'Hardcoded string found')
Issues in program/Cargo.lock:
  - (12, 'Hardcoded string found')
  - (14, 'Line exceeds 80 characters')
  - (38, 'Line exceeds 80 characters')
  - (41, 'Hardcoded string found')
  - (50, 'Hardcoded string found')
  - (65, 'Hardcoded string found')
  - (71, 'Hardcoded string found')
  - (125, 'Hardcoded string found')
  - (131, 'Hardcoded string found')
  - (164, 'Hardcoded string found')
  - (173, 'Hardcoded string found')
  - (177, 'Hardcoded string found')
  - (196, 'Hardcoded string found')
  - (212, 'Hardcoded string found')
  - (216, 'Hardcoded string found')
  - (227, 'Hardcoded string found')
  - (233, 'Hardcoded string found')
  - (245, 'Hardcoded string found')
  - (277, 'Hardcoded string found')
  - (278, 'Hardcoded string found')
  - (317, 'Hardcoded string found')
  - (328, 'Hardcoded string found')
  - (330, 'Hardcoded string found')
  - (349, 'Hardcoded string found')
  - (351, 'Hardcoded string found')
  - (355, 'Hardcoded string found')
  - (358, 'Hardcoded string found')
  - (360, 'Hardcoded string found')
  - (363, 'Hardcoded string found')
  - (365, 'Hardcoded string found')
  - (379, 'Hardcoded string found')
  - (383, 'Hardcoded string found')
  - (385, 'Hardcoded string found')
  - (386, 'Hardcoded string found')
  - (391, 'Hardcoded string found')
  - (401, 'Hardcoded string found')
  - (411, 'Hardcoded string found')
  - (421, 'Hardcoded string found')
  - (428, 'Hardcoded string found')
  - (434, 'Hardcoded string found')
  - (435, 'Hardcoded string found')
  - (439, 'Hardcoded string found')
  - (452, 'Hardcoded string found')
  - (468, 'Hardcoded string found')
  - (478, 'Hardcoded string found')
  - (490, 'Hardcoded string found')
  - (498, 'Hardcoded string found')
  - (499, 'Hardcoded string found')
  - (500, 'Hardcoded string found')
  - (501, 'Hardcoded string found')
  - (506, 'Hardcoded string found')
  - (507, 'Hardcoded string found')
  - (524, 'Hardcoded string found')
  - (537, 'Hardcoded string found')
  - (542, 'Hardcoded string found')
  - (543, 'Hardcoded string found')
  - (544, 'Hardcoded string found')
  - (551, 'Hardcoded string found')
  - (552, 'Hardcoded string found')
  - (569, 'Hardcoded string found')
  - (573, 'Hardcoded string found')
  - (601, 'Hardcoded string found')
  - (606, 'Hardcoded string found')
  - (610, 'Hardcoded string found')
  - (624, 'Hardcoded string found')
  - (631, 'Hardcoded string found')
  - (636, 'Hardcoded string found')
  - (650, 'Hardcoded string found')
  - (728, 'Hardcoded string found')
  - (742, 'Hardcoded string found')
  - (768, 'Hardcoded string found')
  - (826, 'Hardcoded string found')
  - (849, 'Hardcoded string found')
  - (857, 'Hardcoded string found')
  - (877, 'Hardcoded string found')
  - (878, 'Hardcoded string found')
  - (895, 'Hardcoded string found')
  - (899, 'Hardcoded string found')
  - (913, 'Hardcoded string found')
  - (926, 'Hardcoded string found')
  - (934, 'Hardcoded string found')
  - (943, 'Hardcoded string found')
  - (944, 'Hardcoded string found')
  - (956, 'Hardcoded string found')
  - (966, 'Hardcoded string found')
  - (971, 'Hardcoded string found')
  - (981, 'Hardcoded string found')
  - (982, 'Hardcoded string found')
  - (983, 'Line exceeds 80 characters')
  - (996, 'Hardcoded string found')
  - (997, 'Hardcoded string found')
  - (1008, 'Hardcoded string found')
  - (1020, 'Hardcoded string found')
  - (1032, 'Hardcoded string found')
  - (1033, 'Hardcoded string found')
  - (1040, 'Hardcoded string found')
  - (1055, 'Hardcoded string found')
  - (1066, 'Hardcoded string found')
  - (1071, 'Hardcoded string found')
  - (1086, 'Hardcoded string found')
  - (1087, 'Hardcoded string found')
  - (1107, 'Hardcoded string found')
  - (1108, 'Hardcoded string found')
  - (1119, 'Hardcoded string found')
  - (1120, 'Hardcoded string found')
  - (1123, 'Hardcoded string found')
  - (1125, 'Hardcoded string found')
  - (1150, 'Hardcoded string found')
  - (1161, 'Hardcoded string found')
  - (1163, 'Hardcoded string found')
  - (1175, 'Hardcoded string found')
  - (1176, 'Hardcoded string found')
  - (1179, 'Hardcoded string found')
  - (1194, 'Hardcoded string found')
  - (1197, 'Hardcoded string found')
  - (1198, 'Hardcoded string found')
  - (1200, 'Hardcoded string found')
  - (1206, 'Hardcoded string found')
  - (1207, 'Hardcoded string found')
  - (1215, 'Hardcoded string found')
  - (1217, 'Hardcoded string found')
  - (1224, 'Hardcoded string found')
  - (1225, 'Hardcoded string found')
  - (1226, 'Hardcoded string found')
  - (1229, 'Hardcoded string found')
  - (1230, 'Hardcoded string found')
  - (1235, 'Hardcoded string found')
  - (1236, 'Hardcoded string found')
  - (1244, 'Hardcoded string found')
  - (1255, 'Hardcoded string found')
  - (1279, 'Hardcoded string found')
  - (1280, 'Hardcoded string found')
  - (1286, 'Hardcoded string found')
  - (1300, 'Hardcoded string found')
  - (1323, 'Hardcoded string found')
  - (1324, 'Hardcoded string found')
  - (1329, 'Hardcoded string found')
  - (1332, 'Hardcoded string found')
  - (1336, 'Hardcoded string found')
  - (1337, 'Hardcoded string found')
  - (1341, 'Hardcoded string found')
  - (1365, 'Hardcoded string found')
  - (1377, 'Hardcoded string found')
  - (1391, 'Hardcoded string found')
  - (1402, 'Hardcoded string found')
  - (1403, 'Hardcoded string found')
  - (1406, 'Hardcoded string found')
  - (1426, 'Hardcoded string found')
  - (1429, 'Hardcoded string found')
  - (1446, 'Hardcoded string found')
  - (1448, 'Hardcoded string found')
  - (1451, 'Hardcoded string found')
  - (1453, 'Hardcoded string found')
  - (1454, 'Hardcoded string found')
  - (1471, 'Hardcoded string found')
  - (1472, 'Hardcoded string found')
  - (1476, 'Hardcoded string found')
  - (1486, 'Hardcoded string found')
  - (1517, 'Hardcoded string found')
  - (1520, 'Hardcoded string found')
  - (1521, 'Hardcoded string found')
  - (1533, 'Hardcoded string found')
  - (1534, 'Hardcoded string found')
  - (1536, 'Hardcoded string found')
  - (1540, 'Hardcoded string found')
  - (1541, 'Hardcoded string found')
  - (1545, 'Hardcoded string found')
  - (1558, 'Hardcoded string found')
  - (1560, 'Hardcoded string found')
  - (1561, 'Hardcoded string found')
  - (1562, 'Hardcoded string found')
  - (1568, 'Hardcoded string found')
  - (1570, 'Hardcoded string found')
  - (1579, 'Hardcoded string found')
  - (1584, 'Hardcoded string found')
  - (1585, 'Hardcoded string found')
  - (1589, 'Hardcoded string found')
  - (1590, 'Hardcoded string found')
  - (1613, 'Hardcoded string found')
  - (1625, 'Hardcoded string found')
  - (1639, 'Hardcoded string found')
  - (1640, 'Hardcoded string found')
  - (1644, 'Hardcoded string found')
  - (1647, 'Hardcoded string found')
  - (1660, 'Hardcoded string found')
  - (1672, 'Hardcoded string found')
  - (1684, 'Hardcoded string found')
  - (1685, 'Hardcoded string found')
  - (1696, 'Hardcoded string found')
  - (1707, 'Hardcoded string found')
  - (1719, 'Hardcoded string found')
  - (1723, 'Hardcoded string found')
  - (1729, 'Hardcoded string found')
  - (1733, 'Hardcoded string found')
  - (1760, 'Hardcoded string found')
  - (1772, 'Hardcoded string found')
  - (1773, 'Hardcoded string found')
  - (1774, 'Line exceeds 80 characters')
  - (1809, 'Hardcoded string found')
  - (1816, 'Hardcoded string found')
  - (1825, 'Hardcoded string found')
  - (1830, 'Hardcoded string found')
  - (1837, 'Hardcoded string found')
  - (1838, 'Hardcoded string found')
  - (1840, 'Hardcoded string found')
  - (1870, 'Hardcoded string found')
  - (1872, 'Hardcoded string found')
  - (1880, 'Hardcoded string found')
  - (1883, 'Hardcoded string found')
  - (1890, 'Hardcoded string found')
  - (1901, 'Hardcoded string found')
  - (1902, 'Hardcoded string found')
  - (1909, 'Hardcoded string found')
  - (1921, 'Hardcoded string found')
  - (1967, 'Hardcoded string found')
  - (1970, 'Hardcoded string found')
  - (1981, 'Hardcoded string found')
  - (1983, 'Hardcoded string found')
  - (1988, 'Hardcoded string found')
  - (1991, 'Hardcoded string found')
  - (2049, 'Hardcoded string found')
  - (2065, 'Hardcoded string found')
  - (2074, 'Hardcoded string found')
  - (2082, 'Hardcoded string found')
  - (2087, 'Hardcoded string found')
  - (2092, 'Hardcoded string found')
  - (2119, 'Hardcoded string found')
  - (2124, 'Hardcoded string found')
  - (2135, 'Hardcoded string found')
  - (2149, 'Hardcoded string found')
  - (2227, 'Hardcoded string found')
  - (2277, 'Hardcoded string found')
  - (2281, 'Hardcoded string found')
  - (2283, 'Hardcoded string found')
  - (2285, 'Hardcoded string found')
  - (2293, 'Hardcoded string found')
  - (2298, 'Hardcoded string found')
  - (2303, 'Hardcoded string found')
  - (2310, 'Hardcoded string found')
  - (2321, 'Hardcoded string found')
  - (2333, 'Hardcoded string found')
  - (2353, 'Line exceeds 80 characters')
  - (2355, 'Hardcoded string found')
  - (2356, 'Hardcoded string found')
  - (2357, 'Hardcoded string found')
  - (2359, 'Hardcoded string found')
Issues in program/Cargo.toml:
  - (1, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
Issues in program/src/lib.rs:
  - (2, 'Line exceeds 80 characters')
Issues in src/contexts/accounts.tsx:
  - (17, 'Hardcoded string found')
  - (34, 'Hardcoded string found')
  - (63, 'Hardcoded string found')
Issues in src/contexts/connection.tsx:
  - (12, 'Hardcoded string found')
  - (19, 'Line exceeds 80 characters')
  - (31, 'Hardcoded string found')
  - (32, 'Hardcoded string found')
  - (36, 'Hardcoded string found')
  - (37, 'Hardcoded string found')
  - (41, 'Hardcoded string found')
  - (45, 'Hardcoded string found')
  - (46, 'Hardcoded string found')
  - (47, 'Hardcoded string found')
  - (62, 'Line exceeds 80 characters')
  - (63, 'Hardcoded string found')
  - (71, 'Line exceeds 80 characters')
  - (93, 'Hardcoded string found')
  - (100, 'Line exceeds 80 characters')
  - (100, 'Hardcoded string found')
  - (110, 'Line exceeds 80 characters')
Issues in src/contexts/market.tsx:
  - (1, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (31, 'Line exceeds 80 characters')
Issues in src/contexts/wallet.tsx:
  - (14, 'Hardcoded string found')
Issues in src/utils/utils.ts:
  - (18, 'Hardcoded string found')
Issues in src/views/home/index.tsx:
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (35, 'Hardcoded string found')
  - (39, 'Hardcoded string found')
  - (40, 'Line exceeds 80 characters')
Issues in src/wallet-adapters/phantom/index.tsx:
  - (7, 'Hardcoded string found')
  - (8, 'Line exceeds 80 characters')
  - (8, 'Hardcoded string found')
  - (23, 'Line exceeds 80 characters')
  - (38, 'Hardcoded string found')
  - (42, 'Hardcoded string found')
  - (54, 'Line exceeds 80 characters')
  - (83, 'Hardcoded string found')
  - (84, 'Hardcoded string found')
  - (90, 'Hardcoded string found')
  - (91, 'Hardcoded string found')
  - (93, 'Hardcoded string found')
  - (94, 'Hardcoded string found')
Issues in yarn.lock:
  - (7, 'Line exceeds 80 characters')
  - (8, 'Line exceeds 80 characters')
  - (11, 'Line exceeds 80 characters')
  - (12, 'Line exceeds 80 characters')
  - (14, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (20, 'Line exceeds 80 characters')
  - (21, 'Line exceeds 80 characters')
  - (25, 'Line exceeds 80 characters')
  - (26, 'Line exceeds 80 characters')
  - (28, 'Hardcoded string found')
  - (29, 'Hardcoded string found')
  - (30, 'Hardcoded string found')
  - (37, 'Line exceeds 80 characters')
  - (44, 'Line exceeds 80 characters')
  - (45, 'Line exceeds 80 characters')
  - (48, 'Line exceeds 80 characters')
  - (49, 'Line exceeds 80 characters')
  - (51, 'Hardcoded string found')
  - (52, 'Hardcoded string found')
  - (53, 'Hardcoded string found')
  - (54, 'Hardcoded string found')
  - (55, 'Hardcoded string found')
  - (56, 'Hardcoded string found')
  - (57, 'Hardcoded string found')
  - (77, 'Line exceeds 80 characters')
  - (78, 'Line exceeds 80 characters')
  - (84, 'Line exceeds 80 characters')
  - (85, 'Line exceeds 80 characters')
  - (87, 'Hardcoded string found')
  - (88, 'Hardcoded string found')
  - (96, 'Line exceeds 80 characters')
  - (103, 'Line exceeds 80 characters')
  - (104, 'Line exceeds 80 characters')
  - (110, 'Line exceeds 80 characters')
  - (112, 'Line exceeds 80 characters')
  - (113, 'Line exceeds 80 characters')
  - (117, 'Line exceeds 80 characters')
  - (118, 'Line exceeds 80 characters')
  - (121, 'Line exceeds 80 characters')
  - (122, 'Line exceeds 80 characters')
  - (126, 'Line exceeds 80 characters')
  - (127, 'Line exceeds 80 characters')
  - (133, 'Line exceeds 80 characters')
  - (134, 'Line exceeds 80 characters')
  - (136, 'Hardcoded string found')
  - (141, 'Line exceeds 80 characters')
  - (142, 'Line exceeds 80 characters')
  - (144, 'Hardcoded string found')
  - (149, 'Line exceeds 80 characters')
  - (150, 'Line exceeds 80 characters')
  - (152, 'Hardcoded string found')
  - (157, 'Line exceeds 80 characters')
  - (158, 'Line exceeds 80 characters')
  - (160, 'Hardcoded string found')
  - (165, 'Line exceeds 80 characters')
  - (166, 'Line exceeds 80 characters')
  - (168, 'Hardcoded string found')
  - (169, 'Hardcoded string found')
  - (170, 'Hardcoded string found')
  - (171, 'Hardcoded string found')
  - (172, 'Hardcoded string found')
  - (181, 'Line exceeds 80 characters')
  - (182, 'Line exceeds 80 characters')
  - (186, 'Line exceeds 80 characters')
  - (187, 'Line exceeds 80 characters')
  - (190, 'Line exceeds 80 characters')
  - (191, 'Line exceeds 80 characters')
  - (193, 'Hardcoded string found')
  - (194, 'Hardcoded string found')
  - (204, 'Line exceeds 80 characters')
  - (205, 'Line exceeds 80 characters')
  - (209, 'Line exceeds 80 characters')
  - (210, 'Line exceeds 80 characters')
  - (214, 'Line exceeds 80 characters')
  - (215, 'Line exceeds 80 characters')
  - (221, 'Line exceeds 80 characters')
  - (222, 'Line exceeds 80 characters')
  - (225, 'Line exceeds 80 characters')
  - (226, 'Line exceeds 80 characters')
  - (228, 'Hardcoded string found')
  - (229, 'Hardcoded string found')
  - (230, 'Hardcoded string found')
  - (239, 'Line exceeds 80 characters')
  - (240, 'Line exceeds 80 characters')
  - (243, 'Line exceeds 80 characters')
  - (244, 'Line exceeds 80 characters')
  - (246, 'Hardcoded string found')
  - (247, 'Hardcoded string found')
  - (250, 'Hardcoded string found')
  - (258, 'Line exceeds 80 characters')
  - (259, 'Line exceeds 80 characters')
  - (262, 'Line exceeds 80 characters')
  - (263, 'Line exceeds 80 characters')
  - (265, 'Hardcoded string found')
  - (279, 'Line exceeds 80 characters')
  - (280, 'Line exceeds 80 characters')
  - (283, 'Line exceeds 80 characters')
  - (284, 'Line exceeds 80 characters')
  - (286, 'Hardcoded string found')
  - (287, 'Hardcoded string found')
  - (309, 'Line exceeds 80 characters')
  - (310, 'Line exceeds 80 characters')
  - (312, 'Hardcoded string found')
  - (334, 'Hardcoded string found')
  - (335, 'Hardcoded string found')
  - (339, 'Line exceeds 80 characters')
  - (340, 'Line exceeds 80 characters')
  - (344, 'Line exceeds 80 characters')
  - (346, 'Line exceeds 80 characters')
  - (347, 'Line exceeds 80 characters')
  - (351, 'Line exceeds 80 characters')
  - (352, 'Line exceeds 80 characters')
  - (354, 'Hardcoded string found')
  - (359, 'Line exceeds 80 characters')
  - (360, 'Line exceeds 80 characters')
  - (364, 'Line exceeds 80 characters')
  - (371, 'Line exceeds 80 characters')
  - (372, 'Line exceeds 80 characters')
  - (374, 'Hardcoded string found')
  - (381, 'Line exceeds 80 characters')
  - (383, 'Line exceeds 80 characters')
  - (384, 'Line exceeds 80 characters')
  - (388, 'Line exceeds 80 characters')
  - (389, 'Line exceeds 80 characters')
  - (393, 'Line exceeds 80 characters')
  - (395, 'Line exceeds 80 characters')
  - (400, 'Line exceeds 80 characters')
  - (401, 'Line exceeds 80 characters')
  - (408, 'Line exceeds 80 characters')
  - (409, 'Line exceeds 80 characters')
  - (416, 'Line exceeds 80 characters')
  - (423, 'Line exceeds 80 characters')
  - (424, 'Line exceeds 80 characters')
  - (431, 'Line exceeds 80 characters')
  - (433, 'Line exceeds 80 characters')
  - (434, 'Line exceeds 80 characters')
  - (438, 'Line exceeds 80 characters')
  - (439, 'Line exceeds 80 characters')
  - (446, 'Line exceeds 80 characters')
  - (447, 'Line exceeds 80 characters')
  - (453, 'Line exceeds 80 characters')
  - (454, 'Line exceeds 80 characters')
  - (461, 'Line exceeds 80 characters')
  - (467, 'Line exceeds 80 characters')
  - (469, 'Line exceeds 80 characters')
  - (470, 'Line exceeds 80 characters')
  - (472, 'Line exceeds 80 characters')
  - (478, 'Line exceeds 80 characters')
  - (479, 'Line exceeds 80 characters')
  - (480, 'Line exceeds 80 characters')
  - (486, 'Line exceeds 80 characters')
  - (487, 'Line exceeds 80 characters')
  - (493, 'Line exceeds 80 characters')
  - (500, 'Line exceeds 80 characters')
  - (505, 'Line exceeds 80 characters')
  - (507, 'Line exceeds 80 characters')
  - (513, 'Line exceeds 80 characters')
  - (514, 'Line exceeds 80 characters')
  - (516, 'Line exceeds 80 characters')
  - (521, 'Line exceeds 80 characters')
  - (522, 'Line exceeds 80 characters')
  - (526, 'Line exceeds 80 characters')
  - (533, 'Line exceeds 80 characters')
  - (534, 'Line exceeds 80 characters')
  - (538, 'Line exceeds 80 characters')
  - (546, 'Line exceeds 80 characters')
  - (547, 'Line exceeds 80 characters')
  - (549, 'Line exceeds 80 characters')
  - (550, 'Line exceeds 80 characters')
  - (555, 'Line exceeds 80 characters')
  - (556, 'Line exceeds 80 characters')
  - (562, 'Line exceeds 80 characters')
  - (564, 'Line exceeds 80 characters')
  - (565, 'Line exceeds 80 characters')
  - (572, 'Line exceeds 80 characters')
  - (573, 'Line exceeds 80 characters')
  - (577, 'Line exceeds 80 characters')
  - (584, 'Line exceeds 80 characters')
  - (585, 'Line exceeds 80 characters')
  - (589, 'Line exceeds 80 characters')
  - (597, 'Line exceeds 80 characters')
  - (598, 'Line exceeds 80 characters')
  - (602, 'Line exceeds 80 characters')
  - (603, 'Line exceeds 80 characters')
  - (607, 'Line exceeds 80 characters')
  - (614, 'Line exceeds 80 characters')
  - (615, 'Line exceeds 80 characters')
  - (617, 'Hardcoded string found')
  - (622, 'Line exceeds 80 characters')
  - (623, 'Line exceeds 80 characters')
  - (631, 'Line exceeds 80 characters')
  - (638, 'Line exceeds 80 characters')
  - (639, 'Line exceeds 80 characters')
  - (641, 'Hardcoded string found')
  - (642, 'Hardcoded string found')
  - (643, 'Hardcoded string found')
  - (644, 'Hardcoded string found')
  - (655, 'Line exceeds 80 characters')
  - (662, 'Line exceeds 80 characters')
  - (663, 'Line exceeds 80 characters')
  - (667, 'Line exceeds 80 characters')
  - (669, 'Line exceeds 80 characters')
  - (674, 'Line exceeds 80 characters')
  - (679, 'Line exceeds 80 characters')
  - (686, 'Line exceeds 80 characters')
  - (687, 'Line exceeds 80 characters')
  - (693, 'Line exceeds 80 characters')
  - (695, 'Line exceeds 80 characters')
  - (700, 'Line exceeds 80 characters')
  - (701, 'Line exceeds 80 characters')
  - (705, 'Line exceeds 80 characters')
  - (707, 'Line exceeds 80 characters')
  - (708, 'Line exceeds 80 characters')
  - (712, 'Line exceeds 80 characters')
  - (713, 'Line exceeds 80 characters')
  - (715, 'Hardcoded string found')
  - (720, 'Line exceeds 80 characters')
  - (721, 'Line exceeds 80 characters')
  - (728, 'Line exceeds 80 characters')
  - (729, 'Line exceeds 80 characters')
  - (731, 'Line exceeds 80 characters')
  - (732, 'Line exceeds 80 characters')
  - (737, 'Line exceeds 80 characters')
  - (738, 'Line exceeds 80 characters')
  - (740, 'Line exceeds 80 characters')
  - (745, 'Line exceeds 80 characters')
  - (746, 'Line exceeds 80 characters')
  - (750, 'Line exceeds 80 characters')
  - (756, 'Line exceeds 80 characters')
  - (758, 'Line exceeds 80 characters')
  - (759, 'Line exceeds 80 characters')
  - (761, 'Line exceeds 80 characters')
  - (762, 'Line exceeds 80 characters')
  - (766, 'Line exceeds 80 characters')
  - (767, 'Line exceeds 80 characters')
  - (771, 'Line exceeds 80 characters')
  - (778, 'Line exceeds 80 characters')
  - (779, 'Line exceeds 80 characters')
  - (786, 'Line exceeds 80 characters')
  - (788, 'Line exceeds 80 characters')
  - (789, 'Line exceeds 80 characters')
  - (793, 'Line exceeds 80 characters')
  - (794, 'Line exceeds 80 characters')
  - (800, 'Line exceeds 80 characters')
  - (801, 'Line exceeds 80 characters')
  - (803, 'Hardcoded string found')
  - (804, 'Hardcoded string found')
  - (805, 'Hardcoded string found')
  - (806, 'Hardcoded string found')
  - (807, 'Hardcoded string found')
  - (808, 'Hardcoded string found')
  - (816, 'Line exceeds 80 characters')
  - (818, 'Line exceeds 80 characters')
  - (820, 'Line exceeds 80 characters')
  - (821, 'Line exceeds 80 characters')
  - (825, 'Line exceeds 80 characters')
  - (826, 'Line exceeds 80 characters')
  - (835, 'Line exceeds 80 characters')
  - (836, 'Line exceeds 80 characters')
  - (838, 'Hardcoded string found')
  - (848, 'Line exceeds 80 characters')
  - (855, 'Line exceeds 80 characters')
  - (856, 'Line exceeds 80 characters')
  - (858, 'Hardcoded string found')
  - (871, 'Line exceeds 80 characters')
  - (878, 'Line exceeds 80 characters')
  - (879, 'Line exceeds 80 characters')
  - (883, 'Line exceeds 80 characters')
  - (890, 'Line exceeds 80 characters')
  - (891, 'Line exceeds 80 characters')
  - (895, 'Line exceeds 80 characters')
  - (897, 'Line exceeds 80 characters')
  - (898, 'Line exceeds 80 characters')
  - (902, 'Line exceeds 80 characters')
  - (903, 'Line exceeds 80 characters')
  - (907, 'Line exceeds 80 characters')
  - (914, 'Line exceeds 80 characters')
  - (915, 'Line exceeds 80 characters')
  - (919, 'Line exceeds 80 characters')
  - (926, 'Line exceeds 80 characters')
  - (927, 'Line exceeds 80 characters')
  - (931, 'Line exceeds 80 characters')
  - (932, 'Line exceeds 80 characters')
  - (938, 'Line exceeds 80 characters')

**Comment by martinjbrown776** [comment]
I got it.
