### ISSUE TITLE
Issue-feat: style

### ISSUE THREAD

**Issue by kazupot7** [kazupot7/token-creator#8]
Automated Review Comments
Issues in src/App.less:
  - (6, 'Line exceeds 80 characters')
  - (28, 'Hardcoded string found')
Issues in src/ant-custom.less:
  - (6, 'Hardcoded string found')
  - (8, 'Line exceeds 80 characters')
  - (9, 'Line exceeds 80 characters')
  - (10, 'Line exceeds 80 characters')
  - (10, 'Hardcoded string found')
  - (11, 'Line exceeds 80 characters')
  - (11, 'Hardcoded string found')
  - (12, 'Line exceeds 80 characters')
  - (12, 'Hardcoded string found')
Issues in src/components/Layout/index.tsx:
  - (2, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (36, 'Hardcoded string found')
  - (41, 'Hardcoded string found')
  - (42, 'Hardcoded string found')
  - (50, 'Hardcoded string found')
  - (57, 'Hardcoded string found')
  - (65, 'Hardcoded string found')
  - (69, 'Hardcoded string found')
  - (96, 'Hardcoded string found')
  - (101, 'Hardcoded string found')
  - (104, 'Hardcoded string found')
  - (112, 'Hardcoded string found')
  - (115, 'Hardcoded string found')
Issues in src/views/home/index.tsx:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (14, 'TODO found')

**Comment by glory1001** [comment]
I got it.
