### ISSUE TITLE
Issue-Create .gitpod.yml

# Gitpod with solana 1.6.9 by default runs frontend with program on a devnet but also has rust and solana cli so allows user to compile, test and run it too

### ISSUE THREAD

**Issue by kazupot7** [kazupot7/token-creator#86]
Automated Review Comments
Issues in .gitpod.yml:
  - (10, 'Line exceeds 80 characters')
  - (25, 'Line exceeds 80 characters')
  - (25, 'Hardcoded string found')
Issues in program/Cargo.toml:
  - (8, 'Hardcoded string found')

**Comment by glory1001** [comment]
I got it.
